### PR TITLE
new toggle button - closes #284, #625

### LINKED ISSUE #284: Usability issue in the settings: green / red buttons
hi guys,

first of all thanks for the dev of searx, we're currently setting it up here: https://www.privatesearch.io/ 

but I've noticed two usability issues in the preferences menu:

1) it's confusing that "allow" is colored red and "block" is colored green. it would improvie the usability in my opinion to do it the other way around.
2) Some people are red-green color blind: https://en.wikipedia.org/wiki/Color_blindness#Red.E2.80.93green_color_blindness

thanks again for your great work!
bye

searx

### PR DESCRIPTION
**Pull request by kvch**
More intuitive toggle button is introduced to make engine/plugin switching less confusing.

### CODE REVIEW

**Comment by ibrokemypie** [comment]
scrot?

**Comment by kvch** [comment]
Engines
screenshot_2016-08-08_13-53-51

Plugins
screenshot_2016-08-08_13-54-06

**Comment by ibrokemypie** [comment]
Very nice, and very obvious, I like.

**Comment by kvch** [comment]
@PwnArt1st \o/

**Comment by asciimoo** [comment]
awesome, thanks

**Pull request merged**
