### PR TITLE
Adds engines : Youtube with or without API and multiple Qwant

### PR DESCRIPTION
**Pull request by Cqoicebordel**
The API needs an API_KEY.
The NOAPI doesn't have the published dates.

I haven't deleted the old youtube engine just in case, it could be useful in the future if Google changes its mind, but I doubt it.
For the published dates, the page I had was in French, and I was a bit lazy to tweak the cookies to have it as uniform as possible so the date detection would work. I think it's good enough for now, but tell me if I'm wrong. Youtube doesn't provide precise date on its search page anyway, so it would be hard to display something useful.

EDIT : solve #331

### CODE REVIEW

**Comment by Cqoicebordel** [comment]
Added a few Qwant engines : 
- Web
- Images
- News
- Social (seems to provide only results from Twitter, but search efficiently)

A few more possibilities are available from the Qwant 'API' : 
- Knowledge graph (with keyword 'knowledge')
- smart_top
- shopping
- videos (but this one provide only videos from youtube, so I skipped it)

Solve #326 

(and sorry for putting it in the same branch as youtube, it was an error on my part)

**Comment by asciimoo** [comment]
Great! What about implementing all the Qwant engines in a single file to handle different categories like the piratebay engine or swisscows (#348)?

**Comment by Cqoicebordel** [comment]
The difference is that for each type, in qwant, it's a different source of data, like bing or google.
It allow a bigger granularity than TPB for ex. by allowing disabling the images or news sources.
I don't think it would be a good idea to put them in a single file.

**Comment by dalf** [comment]
Perhaps what we miss here it is inheritance using Class and Object.
It could help to have common code at one place.

For now, we have two options :
- With one python module per category it is easy to understand the query and the schema of the result.
- With one python module for all categories, the copy / paste is avoided, but we have to carefully read the code to understand the schema of the result for each category.

**Comment by Cqoicebordel** [comment]
Yes , there is a bit of code redundancy here. But if we look at all the engines, there is _a lot_ a code redundancy.

In this case, I think I used the right approach, because if there was only one python module, it must have done four (4) requests by itself (because it's 4 different urls), and that's not the pattern we used so far : 
Until now, we did a module per request (url).

So, I'm not sure why suddendly it's an issue blocking this merge ?

**Comment by dalf** [comment]
I forgot : my comment was not about why we should block the merge of this PR. Only a brainstorming that should be another "issue". @asciimoo : merge ?

**Comment by asciimoo** [comment]
What's the problem with defining more than one engines/categories in one file if the code is nearly identical? Don't repeat yourself. If there are redundant parts in the code, reduce them instead of writing new ones.
With the current solution an API change requires to modify the code in 4 different places, imho it's not the right approach.

**Comment by Cqoicebordel** [comment]
Ok, I understand.
But in this case, since it's using 4 different URLs, each API can change independantly.
If you want, I'll put them all in a single file, but I strongly think that's the wrong approach here.

**Comment by Cqoicebordel** [comment]
Nevermind, I understood, and I'll propose another way tonight.

**Comment by Cqoicebordel** [comment]
Sorry it took me so long to understand. I tought for a moment you wanted me to perform four requests simultaneously.

Tell me if this way is ok.

**Comment by asciimoo** [comment]
ah, yes, so pretty and much simpler. Just a minor note: maybe a dict which maps categories to keywords would be better than setting `search_url_keyword` in the config.
The actual search category is available from the `request()` function as `params['category']` and as `resp.search_params['category']` from the `response()` function in each engine.

**Comment by Cqoicebordel** [comment]
Agreed, it's much better. With a dict too.

And thanks for the pointers. They weren't the right ones, but thanks anyway ;)

**Comment by asciimoo** [comment]
=]
Thanks!

**Comment by pointhi** [comment]
youtube_api is not working for me:

```
ERROR:searx.search:engine crash: youtube
Traceback (most recent call last):
  File "/usr/local/searx/searx/search.py", line 41, in search_request_wrapper
    return fn(url, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 80, in get
    return request('get', url, **kwargs)
  File "/usr/local/searx/searx/poolrequests.py", line 73, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/sessions.py", line 579, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/usr/local/searx/searx-ve/local/lib/python2.7/site-packages/requests/hooks.py", line 41, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/usr/local/searx/searx/search.py", line 107, in process_callback
    search_results = callback(response)
  File "/usr/local/searx/searx/engines/youtube_api.py", line 56, in response
    videoid = result['id']['videoId']
KeyError: 'videoId'
```

Furthermore, the normal youtube api is also not returning results.

**Pull request merged**
