### PR TITLE
Update OpenSearch Description

### PR DESCRIPTION
**Pull request by GreenLunar**

### CODE REVIEW

**Comment by asciimoo** [comment]
@GreenLunar could you update the tests too? (https://github.com/asciimoo/searx/blob/master/searx/tests/test_webapp.py#L147)

**Comment by GreenLunar** [comment]
Do you know how to do it using GitHub WebUI, without repeating the above edits, all over, again?

**Comment by asciimoo** [comment]
i don't know, I never used the webui for file editing

**Comment by GreenLunar** [comment]
Feel free to reject this PR and make those changes yourself.  I am using pseudo names, anyway.

**Comment by asciimoo** [comment]
okay, thanks

**Comment by GreenLunar** [comment]
I just read the note says "Add more commits by pushing to the master branch on GreenLunar/searx."

I think it worked for me.

**Comment by asciimoo** [comment]
great, thanks!

**Pull request merged**
