### PR TITLE
[RFR] Add 1337x.to engine

### PR DESCRIPTION
**Pull request by johackim**

### CODE REVIEW

**Comment by asciimoo** [comment]
First of all, thank you the new engine. It looks like a fast and well functioning torrent search.
Some thoughts:
 - It would be good to parse seeders/leechers and file size (see `torrentz` engine as an example)
 - I'm not sure if it is good to set it active by default in all categories. There are already torrent engines in `video`/`music` results and I'm not sure it is good if torrent results dominates these categories by default.

**Comment by johackim** [comment]
@asciimoo Thanks for your job, searx is really awesome ! I have added `seed`, `leech`, `filesize` and `icon`.

**Review by asciimoo — APPROVED** [review]

**Comment by asciimoo** [comment]
Great, thanks!

**Comment by Pireo** [comment]
Guys, do you know this program? Sorry for the OT, but I thought you can help here too!
https://github.com/qbittorrent/qBittorrent/wiki/Unofficial-search-plugins

**Comment by johackim** [comment]
Thanks @Pireo ;) I didn't know this program !

**Pull request merged**
