### PR TITLE
[mod] move public instance list to https://searx.space

### PR DESCRIPTION
**Pull request by dalf**
To be merged once https://github.com/dalf/searx-stats2/issues/13 is fixed.

### CODE REVIEW

**Review by return42 — APPROVED** [review]
Thanks for the excellent round-trip!

**Comment by unixfox** [comment]
Maybe you could also link to searx.space here: https://github.com/asciimoo/searx/wiki/Searx-instances?

**Comment by dalf** [comment]
Note: The two meta-instances are missing : https://github.com/asciimoo/searx/blob/e84067816b7d9cd83569a5b90385ba40cbc4e2fe/docs/user/public_instances.rst#meta-searx-instances

**Comment by unixfox** [comment]
You could add it in the about page?

**Comment by dalf** [comment]
@unixfox done.

**Pull request merged**
