### PR TITLE
bing_images & www1x engines use https connections

### PR DESCRIPTION
**Pull request by dalf**
everything is in the title.

### CODE REVIEW

**Comment by Cqoicebordel** [comment]
I have a comment off topic :
I don't know how it's usual done, or if I'm something wrong in my repo, but anytime you create a new branch in this repo, it's created also in every forked repo.
So my request is that, when you want a new branch, to request a pull a little while after, could you create it in your own forked repo ?
Since this repo is the "master" one, I think it should be as clean as possible, having branches only when differents versions of searx must be developped alongside, and not for "tiny" commits (I don't use tiny as a perjorative word here, it's just opposed to a massive overhaul of the codebase).

Anyway, that's my 2 cents, and I may be wrong :)

**Comment by dalf** [comment]
No problem, next branches will be created on my repo, sorry for the annoyance

**Comment by Cqoicebordel** [comment]
Don't worry and thanks a lot :)

**Comment by asciimoo** [comment]
cool, thanks!

**Pull request merged**
