### PR TITLE
Fix IP instant answer

### PR DESCRIPTION
**Pull request by Lamessen**
When you do a research on "ip", duckduckgo send an instant answer with the IP adress of the searx server, which is not useful.
This fix gives to user the ip adress that he uses to access searx.

### CODE REVIEW

**Comment by pointhi** [comment]
I think we should add Widget/Plugin support, to support such features #60.

**Comment by ldidry** [comment]
I don't think so (or at least, not now):
- as I can see on your issue, plugins are not ready
- right now, searx returns a false answer, which is _really_ bad for the user and searx reputation

**Comment by Cqoicebordel** [comment]
+1 to both.

We should work on widget/plugin as soon as possible.

**Comment by dalf** [comment]
+1 for widget / plugin system

EDIT : In my opinion, the fix should be in duckduckgo_definitions.py not in webapp.py

If I activate the zealot mode about privacy : searx shouldn't answer THIS question because, it's mean that the browser IP value will be spread over all the code.

If we talk about privacy we should even advice this in nginx configuration : 

```
uwsgi_param REMOTE_ADDR 127.0.0.1;
```

**Comment by ldidry** [comment]
Don't you think it would be a good thing to merge this commit and revert it when the plugin system will be ready?

**Comment by dalf** [comment]
All these queries give the IP address : 
- ip
- what is my ip
- what is my ip address

I suggest that
- duckduckgo_definitions.py detect the answser "Your IP address is ..."
- and either ignore this answer, or replace it with the right one.

**Comment by ldidry** [comment]
There is now a plugin for that, introduced in commit 00cc4dcbf44d9ecea89befb08cae4ee5561c4247  
I think this PR can be closed, no?

**Comment by Lamessen** [comment]
plugin now exists for that

**Pull request closed without merging**
