### PR TITLE
Simple theme

### PR DESCRIPTION
**Pull request by dalf**
Based on legacy theme, this theme is a copy cat of some existing layout.

Only the results page is modified for now, and still unfinished.

A not exhaustive TODO list :
- [x] mootools can be replaced by https://github.com/autocompletejs/autocomplete.js to create less heavy pages (minus 90k).
- [x] be able to include javascript only if needed (no need to include the image layout javascript if there is no image result)
- [x] use grunt to concat, minimize the javascript files.
- [ ] results page : consistent layout, tweak some details 
- [ ] results page / index page : double check all form parameters (pass all parameters : safesearch and all) 
- [ ] image template : improve display ( https://www.sitepoint.com/recreating-google-images-search-layout-css/ ?)
- [ ] default template : fix height of small image (object-fit and object-position display the real size image, but the overall size remains big). Example : search for "osmand" with the file category.  
- [x] index page layout
- [x] preferences page layout
- [x] map template doesn't work
- [x] torrent template is broken
- [x] video player
- [x] music player
- [x] vim_hotkeys plugin
- [x] search_on_category_select plugin
- [x] open_results_on_new_tab plugin
- [ ] infinite_scroll plugin
- [x] mobile layout, test responsive design.
- [ ] update the RTL style

Related to #828 and #687

capture d ecran de 2017-02-12 15-25-34

capture d ecran de 2017-02-12 15-27-25

capture d ecran de 2017-02-12 15-29-08

capture d ecran de 2017-05-13 13-36-08

### CODE REVIEW

**Comment by dalf** [comment]
I've updated my instance with the simple branch : https://al-f.net/searx/ so everyone can give a try and add bugs reports, reviews, comments. 

### About network usage
A result page without images and without autocompleter downloads 37,6Kb. With autocompleted activated, 67.9kb are downloaded (using mootools, http://autocomplete-js.com/ can be used but seems buggy).

More over, the full glyphicons-halflings font is downloaded (17.7kb): a subset can be created to reduce the network usage (may be 10kb less ?).

The magnify can be replace by an icons ( glyphicon-search ) : 2.3kb.

### About plugins
They are heavily tied to jquery (and the oscar templates). In simple theme, a quick implementation is to load jquery when a plugin add some js files. A more long term is to implement plugin with native javascript (or to transpile from ES6 / ES7). Another third way is to [load minimal jquery](http://projects.jga.me/jquery-builder/) version, or use a compatible version like [zepto](http://zeptojs.com/).

**Comment by dalf** [comment]
Some updates : 
* without image, the network usage is 22.1kb for results of the general category. 
* the vim keyboard has been included and modify to use vanilla JS (the help doesn't work for now)
* the browser focus follows the vim selection
* images size are set in a way that each row is always full (the last commit fixes a bug when there are different block of images)   
* the autocompleter uses POST when the main search uses POST too. 

What can improved : 
* search, the input has the focus, go to another page, go back to the searx page : the autocomplete choices are shown. I don't think the user expects that behaviour.
* the "send search on category click" is missing.
* still the preferences page.
* use the full page width when the user search for images only.
* which logo to used ?
* the customize ion font could be included in the css which should reduce the response time.
* refactor the less sources : for now, I think the RTL modification won't be easy.

**Comment by dalf** [comment]
There are still plenty of different things to do, but I think it could be the time to merge, so more people could test it, or even contribute, @asciimoo what do you think ? 

It is more than usable except with RTL languages.

**Review by asciimoo — APPROVED** [review]
Thank you.

**Comment by dalf** [comment]
see for remaining work on the simple theme : https://github.com/asciimoo/searx/issues/1025

**Pull request merged**
