### PR TITLE
nyaa.si fixed

### PR DESCRIPTION
**Pull request by misnyo**
also dependency for this engine has been removed in another engine

### CODE REVIEW

**Review by kvch — APPROVED** [review]
I approve, but `int_or_zero` could be extracted into searx.utils and could be used in other torrent engines. But it is up to you if you do it or not.

**Comment by misnyo** [comment]
Sorry for the accidental close of the PR, will update with the `int_or_zero` issue soon.

**Comment by misnyo** [comment]
I guess this should be good for now;)

**Review by asciimoo — APPROVED** [review]
👍

**Pull request merged**
