### PR TITLE
[themes] add hyperlink to searx instances list in error message

### LINKED ISSUE #2383: Add hyperlink to searx public instances list in Error massage
**Is your feature request related to a problem? Please describe.**

_Error! Engines cannot retrieve results._
_torrentz (timeout), btdigg (CAPTCHA required)_
_Please, try again later or find another searx instance._

**Describe the solution you'd like**

"searx instance" should be hyperlinked https://searx.space/

### PR DESCRIPTION
**Pull request by return42**
closes: #2383

### CODE REVIEW

**Comment by unixfox** [comment]
It would be great to explain what's searx.space in a short description because just pasting the link of searx.space doesn't mean much for a beginner.

**Comment by return42** [comment]
> It would be great to explain what's searx.space in a short description 

Hard to translate in all the languages the UI supports ... this is only a error message / for the first it should be enough to add simply the link.

**Comment by dalf** [comment]
https://github.com/searx/searx/blob/36600118fb3e40ebd172245941306943581ef6f8/searx/templates/oscar/base.html#L91

There is already link to searx.space at the bottom of the pages, we can be use it :

`<p><small>{{ _('Please, try again later or find another searx instance.') }} ( <a href="{{ brand.PUBLIC_INSTANCES }}">{{ _('Public instances') }}</a> )</p>`

**Comment by return42** [comment]
> There is already link to searx.space 

@dalf thanks for the hint .. I fixed the patch to use `brand.PUBLIC_INSTANCES`

**Comment by dalf** [comment]
Thank you!

**Pull request merged**
