### PR TITLE
[enh] show spelling corrections

### PR DESCRIPTION
**Pull request by davidar**
Like #189 but using corrections provided by engines.

### CODE REVIEW

**Comment by asciimoo** [comment]
Useful feature! Could you add it to the `json` output too? I think it would be useful to get this information in that form too.

**Comment by davidar** [comment]
@asciimoo done

**Review by asciimoo — APPROVED** [review]

**Comment by asciimoo** [comment]
Great, thanks

**Review by asciimoo — CHANGES_REQUESTED** [review]
Please fix the failing test

**Comment by davidar** [comment]
oops, fixed

**Review by asciimoo — APPROVED** [review]

**Comment by asciimoo** [comment]
Thank you

**Pull request merged**
