### PR TITLE
[mod] add a search_one_request_safe function wrapper

### PR DESCRIPTION
**Pull request by dalf**
Add a search_one_request_safe function wrapper to call search_one_request. 
All exceptions are catched in this wrapper.

Note that ```if search_duration > timeout_limit + timeout_overhead``` check is done before setting ```engine.continuous_errors = 0```.

### CODE REVIEW

**Review by asciimoo — APPROVED** [review]

**Comment by asciimoo** [comment]
Thank you

**Comment by asciimoo** [comment]
@dalf how can cause problem the mentioned search duration check?

**Comment by dalf** [comment]
Not sure if I understand correctly your question. 

Without this commit : 
* if an engine get a timeout with Requests, it will be suspended.
* if an engine get a timeout with searx (the ```if search_duration > timeout_limit + timeout_overhead``` check), the engine will not be suspended

With this commit, in both case the engine will be suspended. 

Actually the ```if search_duration > timeout_limit + timeout_overhead``` check could be part of poolrequests.py. The purpose is to have a global timeout, not a timeout for the connect, and another one for the read.

**Comment by asciimoo** [comment]
ah, i see, great, thanks.
Global+read timeout sounds reasonable to me.

**Pull request merged**
