### PR TITLE
add additional search language

### PR DESCRIPTION
**Pull request by miicha**
Up to now it is a working, but kind of quick and dirty implementation of an additional search language. Drawbacks are: 
- additional querys
- only one additional language
- language not user configurable

### CODE REVIEW

**Comment by return42** [comment]
Hi @miicha, apologize our late reply ...

> but kind of quick and dirty implementation of an additional search language. 

Do you have time and interest to complete implementation? ..  I can understand if you have lost interest in the meantime ..

**Comment by miicha** [comment]
@return42 I'm still interested in completing that feature but probably no time to work much on it for the next month. So I can totally understand if someone want's to start/continue working on that feature.

**Comment by return42** [comment]
In the meantime we had various changes about the search and UI language, compare e.g. https://github.com/asciimoo/searx/pull/1621 and https://github.com/asciimoo/searx/pull/1860

I guess they address the similar question, so I close this PR for the first. If I am wrong, please send a note and I reopen the PR again.

**Comment by miicha** [comment]
These two adress other issues if I'm not mistaken. The point of that PR
was to do a search in english (or another language) as well as the user
selected language. Therefore I could also open another pull request...

But in the end the quick fix works quite well even though it asks every
search engine twice and I don't know how to avoid that.


Am 25.02.2020 um 09:37 schrieb Markus Heiser:

**Comment by return42** [comment]
> to do a search in english (or another language) as well as the user selected language. 

thanks for clarifying!

> even though it asks every search engine twice and I don't know how to avoid that.

The idea is good / quering twice won't be merged, so I left this closed.

If you have any idea how we can solve this problem, create an issue and we can discuss it.

**Pull request closed without merging**
