### PR TITLE
Fix YaCy engine

### PR DESCRIPTION
**Pull request by 0xhtml**
This fixes a bug were the favicons of the general YaCy search results got interpreted as images.

### CODE REVIEW

**Comment by 0xhtml** [comment]
How is it decided if and when this pull request gets merged?
And should I update my pull request to the latest state of `master`?

**Comment by 0xhtml** [comment]
I also added a small enhancement to the yacy engine: It now supports http authentication.

**Comment by ghost** [comment]
While your at it 0xhtml, are you going to add support for "some search words /language/en" ? Yacy supports that. And yes, I know it's a stupid way to support languages but that's what yacy supports.

**Comment by HLFH** [comment]
It would be great to merge this PR @asciimoo @dalf.

It fixes the following bug (got this error with searx-checker): **AttributeError: 'NoneType' object has no attribute 'startswith'**

> juin 23 17:04:41 arch-server.example.com python3[2040757]: yacy.Traceback (most recent call last):
juin 23 17:04:41 arch-server.example.com python3[2040757]:   File "checker/checker.py", line 228, in <module>
juin 23 17:04:41 arch-server.example.com python3[2040757]:     main(args.url, args.o)
juin 23 17:04:41 arch-server.example.com python3[2040757]:   File "checker/checker.py", line 215, in main
juin 23 17:04:41 arch-server.example.com python3[2040757]:     state = check_engines_state(instance_url, engines)
juin 23 17:04:41 arch-server.example.com python3[2040757]:   File "checker/checker.py", line 168, in check_engines_state
juin 23 17:04:41 arch-server.example.com python3[2040757]:     provides_results = _request_results(instance_url, engine)
juin 23 17:04:41 arch-server.example.com python3[2040757]:   File "checker/checker.py", line 156, in _request_results
juin 23 17:04:41 arch-server.example.com python3[2040757]:     engine_result = _query_engine_result(instance_url, engine, query)
juin 23 17:04:41 arch-server.example.com python3[2040757]:   File "checker/checker.py", line 146, in _query_engine_result
juin 23 17:04:41 arch-server.example.com python3[2040757]:     return _check_response(resp)
juin 23 17:04:41 arch-server.example.com python3[2040757]:   File "checker/checker.py", line 132, in _check_response
juin 23 17:04:41 arch-server.example.com python3[2040757]:     return _check_results(resp_json['results'])
juin 23 17:04:41 arch-server.example.com python3[2040757]:   File "checker/checker.py", line 86, in _check_results
juin 23 17:04:41 arch-server.example.com python3[2040757]:     if not _check_result(result):
juin 23 17:04:41 arch-server.example.com python3[2040757]:   File "checker/checker.py", line 78, in _check_result
juin 23 17:04:41 arch-server.example.com python3[2040757]:     return _is_url_image(result.get('thumbnail_src'))
juin 23 17:04:41 arch-server.example.com python3[2040757]:   File "checker/checker.py", line 42, in _is_url_image
juin 23 17:04:41 arch-server.example.com python3[2040757]:     if image_url.startswith('//'):
juin 23 17:04:41 arch-server.example.com python3[2040757]: AttributeError: 'NoneType' object has no attribute 'startswith'

**Pull request closed without merging**
