### PR TITLE
Windows does not support SIGUSR1, so don't use it unconditionally.

### PR DESCRIPTION
**Pull request by cyclaero**
### What does this PR do?

Windows does not support SIGUSR1, and in order to get searx run on Windows machines, SIGUSR1 must not be used before checking that it exists.   

### Why is this change important?

Without this change, searx does crash on Windows machines.

### How to test this PR locally?

1. On Windows 7, 8 or 10, install a recent Python release for all users
2. Start cmd.exe
3. Enter the following commands:
- "C:\Program Files\Python3x-xx\Scripts\pip.exe" install pyyaml
- py "C:\path\to\searx-master\setup.py" install
- py "C:\Program Files\Python3x-xx\Lib\site-packages\searx-0.18.0-py3.x.egg\searx\webapp.py

Without the change, webapp.py would crash. With the change, it would launch properly

### Related issues

see: #2653

### CODE REVIEW

**Review by kvch — APPROVED** [review]
Please rebase your PR.

**Comment by cyclaero** [comment]
> Please rebase your PR.

I guess I spoiled it.

I used this tutorial for rebasing https://anavarre.net/how-to-rebase-a-github-pull-request/, and it worked out up to the last line. But then for some reason this f**cking git wants to push my branch with my pull request to the upstream repository, and here of course I don’t have (and I don’t want) write access rights.

I tried now for 2 hours to recover from this without avail. I spent the whole afternoon yesterday to assemble two pull requests which amounts in total to a change of 4 lines of code. There must be a more simple way, 7 hours of work, for nothing. I have better things to do.

So either somebody tells me exactly the command sequence, how I would rebase my pull-request in 5 min, or I start over completely again, and send new pull requests.

**Comment by return42** [comment]
> So either somebody tells me exactly the command sequence, how I would rebase my pull-request in 5 min

Depends where you are .. if you have cloned your fork, checked out your conditional-sigusr1 branch (and origin is your fork):

    git push -f origin conditional-sigusr1

should do the job.

> But then for some reason this f**cking git wants to push my branch

Sorry but here you are at **git**-hub  (notice the syllable 'git' in github) .. you should teach yourself some git workflow basics .. its worth .. it is the way developers will collaborate the next 20 years.

BTW: there is an excellent documentation with [examples](https://git-scm.com/docs/git-push#_examples) and at atlassian you will find a excellent description of some basic  [git workflows](https://www.atlassian.com/git/tutorials/comparing-workflows)

**Review by dalf — APPROVED** [review]

**Comment by cyclaero** [comment]
Thank you very much.

**Pull request merged**
