### PR TITLE
Fix Nginx subdir URL install docs which allowed download of settings.yml

### LINKED ISSUE #1617: [docs] Nginx subdirectory URL example allows download of settings.yml
There is an issue with the setup example in https://asciimoo.github.io/searx/dev/install/installation.html#installation for subdirectory URL deployments:

```nginx
root /usr/local/searx;

location = /searx { rewrite ^ /searx/; }
# location /searx {
        try_files $uri @searx;
}
location @searx {
        uwsgi_param SCRIPT_NAME /searx;
        include uwsgi_params;
        uwsgi_modifier1 30;
        uwsgi_pass unix:/run/uwsgi/app/searx/socket;
}
```

`try_files` causes Nginx to search for files in the server root first. If it matches a file, it is returned. Only if no file matched, the request is passed to uwsgi. The worst consequence I can think of is that  `settings.yml` can be downloaded without authentication (where secrets and configuration details are stored).

To fix this, I propose:

```nginx
location = /searx {
        rewrite ^ /searx/;
}

location /searx/static {
}

location /searx {
        uwsgi_param SCRIPT_NAME /searx;
        include uwsgi_params;
        uwsgi_pass unix:/run/uwsgi/app/searx/socket;
}
```

And add

```
route-run = fixpathinfo:
```

to `/etc/uwsgi/apps-available/searx.ini` because `uwsgi_modifier1 30` is apparently deprecated. Ref: https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.11.html#fixpathinfo-routing-action

I assume this issue exists because some uwsgi upstream docs also use the `try_files` construct (at least I have seen this somewhere in the docs or somewhere else on the Internet but cannot find it right now again).

https://uwsgi-docs.readthedocs.io/en/latest/Nginx.html#hosting-multiple-apps-in-the-same-process-aka-managing-script-name-and-path-info also warns about this:

> If used incorrectly a configuration like this may cause security problems. For your sanity’s sake, double-triple-quadruple check that your application files, configuration files and any other sensitive files are outside of the root of the static files.

### PR DESCRIPTION
**Pull request by ypid**
Closes: #1617

### CODE REVIEW

**Review by kvch — DISMISSED** [review]
Please add also the `.txt` and `.html` files as requested here: https://asciimoo.github.io/searx/dev/contribution_guide.html#documentation

**Comment by ypid** [comment]
Done that. Note that there is room for improvement. Contributors should not need to generate the docs and commit the output. In my case, I use Debian so I might not run the latest and greatest Software for a reason.

Ideally the docs are tested using CI and deployed using readthedocs for example.

That just as an idea. I know that maintaining a Free Software project takes many hours of volunteer work. Thanks and keep up the good work!

**Comment by return42** [comment]
@ypid I hardly dare to say it: but we have postponed the documentary in the meantime (PR #1767) . 

In short: the sources of the docs has been moved from gh-branch to master branch folder docs .. the build  and deploy of the HTML format on gh-pages is no longer done by PRs .. that simplifies the doc workflow for contributors.

Do you have time again and want to adapt the new documentary at /doc ?  I can understand if not and apologize for the inconvenience due to our late response on your PR.

If you are interested in, a good starting point is to read https://asciimoo.github.io/searx/dev/makefile.html#make-docs-docs-live-docs-clean  from thes 3 lines you will linked to what you need to know.  OT: a reST primer iis available from here https://asciimoo.github.io/searx/dev/reST.html

Thanks for being patience with us.

**Comment by ypid** [comment]
Done that. Thanks for stepping up to help!

**Review by return42 — APPROVED** [review]
Thanks!!

**Comment by return42** [comment]
FYI: deployed, see https://asciimoo.github.io/searx/admin/installation.html#with-nginx

**Pull request merged**
