### PR TITLE
New search engine: IPFS search

### PR DESCRIPTION
**Pull request by elpoelma**
## What does this PR do?

This PR adds support for the IPFS search engine (https://ipfs-search.com/).

It adds support for general, video, music and video search.

## Why is this change important?

It allows searX users to search documents which are hosted on distributed IPFS nodes. It widens the amount of options searX users can choose between when selecting search engines.

## How to test this PR locally?

Execute ```make run```.
Turn on IPFS Search on the searX preferences page.

### CODE REVIEW

**Comment by kvch** [comment]
@elpoelma Sorry for taking too long to review your PR. One of the jobs is failing, could you please fix your code?

**Review by kvch — DISMISSED** [review]

**Comment by kvch** [comment]
Thanks! @elpoelma Is this PR ready to be merged? Are you working on language and time range support?

**Comment by elpoelma** [comment]
@kvch I will still look into language and time range support.

**Comment by elpoelma** [comment]
I added support for time ranges, but did not add support for languages as ipfs-search does not support this yet IIRC.

**Review by kvch — APPROVED** [review]
Thank you!

**Pull request merged**
