### PR TITLE
RFC: add searx/settings_default.py

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

* searx loads `searx/settings.yml` into the `settings` variable.
* then, the default values are defined usually using this pattern similar to `settings[....].get('aVariable', default)` 
* it fails for `settings['ui']['static_path']`, see https://github.com/searx/searx/issues/2252#issuecomment-764755567

This PR adds a new function `searx.settings_set_defaults.settings_set_defaults` to set all the default values in one place.

Then instead of 
```
static_path = get_resources_directory(searx_dir, 'static', settings['ui']['static_path'])
```

It is possible to write ```settings['ui']['static_path']```

## Why is this change important?

See https://github.com/searx/searx/issues/2252#issuecomment-764755567 (more precisely the `static_path` definition)

This PR is request for comment / for archive : most probably a better solution is to create some classes in similar way to the `*Settings` classes.

## How to test this PR locally?

The various defaults work as before.
https://github.com/dalf/searx/blob/d82185ad52e042db9d506bc952f5fbf8b8138b99/searx/settings_defaults.py#L93-L126

### CODE REVIEW

**Comment by return42** [comment]
> This PR is request for comment / for archive : most probably a better solution is to create some classes in similar way to the *Settings classes.

I think this PR has its own value  ... cleaning up the stat_path mess .. better solutions can be implemented afterwards on top of this PR.

**Comment by kvch** [comment]
@dalf Is this PR ready for review? Or why is a draft?

**Review by kvch — COMMENTED** [review]
The general sentiment behind the PR is good. I like how you moved initialization of several things into one single file. 

I am interested why did you choose to create a schema like this. We already have a method/approach to parsing settings-like data from dictionaries in `preferences.py`. Is that way not suitable for parsing `settings.yml`? Or alternatively why not create a Settings object with typed attributes?

**Comment by dalf** [comment]
> We already have a method/approach to parsing settings-like data from dictionaries in preferences.py.

preferences.py:
* describes a set of (key, value)
* entangled the values with the read / write operations (from and to cookies & HTML form).

The `settings` variable is a tree without error checking. In the master branch, the default values are set when the code needs them.

I agree it would better to merge two, but that's not a simple task.

-----

This is out of topic: if Settings & Preferences are classes:
* at application level : 
     * a `engine_list` method returns the engines described in `settings.yml` (so the tests are easy to write).
* from a request:
     * the constructor takes the settings at application level (it is already [more or less the case](https://github.com/searx/searx/blob/640d6ce77877551361b0acd116a9cd7faf47c611/searx/preferences.py#L325) )
     * the `engine_list` method returns only the visible engines. The `Preferences` class already has the [`validate_token`](https://github.com/searx/searx/blob/640d6ce77877551361b0acd116a9cd7faf47c611/searx/preferences.py#L515) but engine lst is throw away in the constructor of Preferences.

The `engine_list` is just an example, the general idea is to have. 
Tests would be much more easier to write.

Load / save the user preferences are managed in a different class (or at least remove the [`resp.set_cookie`](https://github.com/searx/searx/blob/640d6ce77877551361b0acd116a9cd7faf47c611/searx/preferences.py#L130) call in each `Setting` class).

That's only my opinion.

**Comment by kvch** [comment]
> > We already have a method/approach to parsing settings-like data from dictionaries in preferences.py.
> 
> preferences.py:
> 
>   * describes a set of (key, value)
>   * entangled the values with the read / write operations (from and to cookies & HTML form).
> 
> 
> The `settings` variable is a tree without error checking. In the master branch, the default values are set when the code needs them.
> 
> I agree it would better to merge two, but that's not a simple task.

I am sorry if I was not clear. I did not say we should merge the two. `Preferences` has more responsibilities than simply parsing preferences. It also sets those in cookies, shows them in the UI. Maybe we could generalize a few parts of it, but I do not think it is worth the effort.

My question about the other approach is not answered. And I am still curious about why not introduce a `Settings` class with all the available attributes (please ignore the naming in the example above, it can be done better probably) like this:

```python
class General:
    def __init__(self):
        self.debug_mode = False

# and so on for all setting groups...

# finally the "big" instance settings class which includes all setting groups
class Settings:
    def __init__(self):
        self.general = General()
        self.brand = Brand()
        self.search = Search()
        self.server = Server()
```

It is true that you had added a constructor which is awesome. But why not go all the way and add the specific class(es)?

**Comment by return42** [comment]
> But why not go all the way and add the specific class(es)?

FWIW that is what I thought also :-)

**Pull request closed without merging**
