### PR TITLE
[enh] timeout and total HTTP time are managed by searx.poolrequests

### PR DESCRIPTION
**Pull request by dalf**
Implement #975

### CODE REVIEW

**Comment by dalf** [comment]
About [```if search_duration > timeout + timeout_overhead```](https://github.com/asciimoo/searx/pull/977/files#diff-678059f39d0697a791718f3a0ddb2f8fR114)
I don't know if it is relevant to keep it ?

Without it, it means the parsed results will be ignored later, inside ```search_multiple_requests```

In addition, this code in search.py
```python
user_agent = gen_useragent()
...
request_params['headers']['User-Agent'] = user_agent
```
could be changed to have a default user agent on all HTTP requests. The default headers could be set at the beginning of ```search_one_request_safe``` (or perhaps ```search_one_request```) using ```poolrequests.set_headers_for_thread```

**Comment by dalf** [comment]
Since a new version has been released, what about merging this one, and take time to test it in master branch ?

**Comment by asciimoo** [comment]
I agree, this is the good time to experiment. We could do the same with #1034.

**Review by asciimoo — APPROVED** [review]
👍

**Pull request merged**
