### PR TITLE
Mod engines init

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

Revert PR #2232 and #2230

webapp.py: Always call `initialize engines` except on the first run of werkzeug with the reload feature.
    
reload is activated when:
* searx_debug is True (SEARX_DEBUG environment variable or settings.yml)
* `FLASK_APP=searx/webapp.py FLASK_ENV=development flask run` (see https://flask.palletsprojects.com/en/1.1.x/cli/ )

Remove  `os.environ.get('UWSGI_ORIGINAL_PROC_NAME') is not None`: the code in this PR detects that ```__name__ != "__main__"``` (searx.webapp was imported).

```__name__ != "__main__"``` works for ```make test``` and ```make docs``` too.
    
## Why is this change important?

Fix `SEARX_DEBUG=0 make docs`
See https://github.com/searx/searx/issues/2204#issuecomment-701373438

## How to test this PR locally?

* `SEARX_DEBUG=0 make docs` : check docs/admin/engines.rst  (check the page contains the engine list).
* `SEARX_DEBUG=1 make docs`: check docs/admin/engines.rst
* `SEARX_DEBUG=0 python searx/webapp.py`: check engines are initialized once.
* `SEARX_DEBUG=1 python searx/webapp.py`: check engines are initialized once, check reload works as intended.
* `make docker`: check if the docker image works as expetected.
* `FLASK_APP=searx/webapp.py flask run` : check engines are initialized once.
* `FLASK_APP=searx/webapp.py FLASK_ENV=development flask run` : check engines are initialized once, check reload works as intended.

## Related issues

* #2204
* #2232
* #2230

### CODE REVIEW

**Comment by dalf** [comment]
@return42 can you have a look ?

**Comment by return42** [comment]
Yes I already added it on my ToDo ist ;) .. but today I do not have time for. I am sorry, I hope I can check it on sunday

**Comment by return42** [comment]
Thanks a lot for doing this work! Except docker, I have tested your suggestions and all works like a charme.   Just some nits ...

    SEARX_DEBUG=0 python searx/webapp.py

depends on the OS.  E.g. on my OS `python` starts a Python 2 session and using the `python3` command ends in:

````
Traceback (most recent call last):
  File "searx/webapp.py", line 49, in <module>
    from werkzeug.middleware.proxy_fix import ProxyFix
ModuleNotFoundError: No module named 'werkzeug'
````
I recommend to test by using python from the pyenv(install):

    $ make clean pyenvinstall
    $ SEARX_DEBUG=0 ./local/py3/bin/python searx/webapp.py
    $ SEARX_DEBUG=1 ./local/py3/bin/python searx/webapp.py

Same said about 'flask' command; use it from the pyenv(install):

    $ FLASK_APP=searx/webapp.py ./local/py3/bin/flask run
    $ FLASK_APP=searx/webapp.py FLASK_ENV=development ./local/py3/bin/flask run

No KO criteria but fore more readability I prefer to use brackets and indent the conditions instead of quoting line-ends.  I fetched your `mod-engines-init` branch / This is a diff, showing what I mean:

````diff
diff --git a/searx/webapp.py b/searx/webapp.py
index c8981a2d..8c05b635 100755
--- a/searx/webapp.py
+++ b/searx/webapp.py
@@ -116,17 +116,26 @@ app.secret_key = settings['server']['secret_key']
 
 # see https://flask.palletsprojects.com/en/1.1.x/cli/
 # True if "FLASK_APP=searx/webapp.py FLASK_ENV=development flask run"
-flask_run_development = os.environ.get("FLASK_APP") is not None and os.environ.get("FLASK_ENV") == 'development'\
+flask_run_development = bool(
+    os.environ.get("FLASK_APP") is not None
+    and os.environ.get("FLASK_ENV") == 'development'
     and is_flask_run_cmdline()
+    )
 
 # True if reload feature is activated of werkzeug, False otherwise (including uwsgi, etc..)
 #  __name__ != "__main__" if searx.webapp is imported (make test, make docs, uwsgi...)
 # see run() at the end of this file : searx_debug activates the reload feature.
-werkzeug_reloader = (searx_debug and __name__ == "__main__") or flask_run_development
+werkzeug_reloader = bool(
+    flask_run_development
+    or (searx_debug and __name__ == "__main__")
+)
+
 
 # initialize the engines except on the first run of the werkzeug server.
-if not werkzeug_reloader\
-   or (werkzeug_reloader and os.environ.get("WERKZEUG_RUN_MAIN") == "true"):
+if ( not werkzeug_reloader
+     or (werkzeug_reloader
+         and os.environ.get("WERKZEUG_RUN_MAIN") == "true") ):
+
     initialize_engines(settings['engines'])
 
 babel = Babel(app)
````

**Comment by dalf** [comment]
> depends on the OS. E.g. on my OS python starts a Python 2 session

I've forgotten to say that I activate the virtualenv: ```. ./local/py3/bin/activate```, then ```python```, ```flask``` etc... works as expected.

About the readability, the ```bool(...)``` doesn't help in my opinion.

I've changed the code to put simple conditions at first, then "complex" one at the end.

Anyway:
* it should be a function ( ```must_run_initialization```)
* but with starlette (new architecture), the things will be different, and this code will be removed.

**Pull request merged**
