### PR TITLE
Update path to wikidata image

### LINKED ISSUE #1341: Searx.me Person Information Missing Picture
I noticed recently that if you search for example "Bill Gates" or another famous person, if you check the right area where there is Wikipedia info and a picture at the top, the picture is missing, it is corrupted.

### PR DESCRIPTION
**Pull request by bourrel**
Fix #1341 by improving media path precision and so removing file metadata

### CODE REVIEW

**Review by asciimoo — APPROVED** [review]
Great, thanks!

**Comment by asciimoo** [comment]
Please fix the formatting: https://travis-ci.org/asciimoo/searx/jobs/400304833#L706

**Comment by bourrel** [comment]
This should fix the formatting.
I also fixed the wikidata tests to work with the updated image path.

**Review by asciimoo — APPROVED** [review]
👍

**Pull request merged**
