### PR TITLE
[fix] fix travis build

### PR DESCRIPTION
**Pull request by dalf**
try to fix the selenium tests by upgrading te geckodriver and selenium version.

### CODE REVIEW

**Comment by asciimoo** [comment]
Great.
Now it has version issues: `WebDriverException: Message: Can't load the profile. Possible firefox version mismatch. You must use GeckoDriver instead for Firefox 48+. Profile Dir: /tmp/tmppRU3uN If you specified a log_file in the FirefoxBinary constructor, check it for details. `


And, there is an other error: `./manage.sh: 83: ./manage.sh: lessc: not found` when running `./manage.sh styles`. Could you investigate it too?

**Comment by dalf** [comment]
The status on travis is ```build:failing``` but everything seems alright except : 

> [!] Grunt build : oscar theme
> ...
> Running "less:bootstrap" (less) task
>Destination not written because no source files were found.

**Review by asciimoo — CHANGES_REQUESTED** [review]
Awesome && respect!
Please surround shell variables with double quotes, especially paths.

**Review by asciimoo — APPROVED** [review]
Awesome! Thanks.

**Comment by dalf** [comment]
It seems that the coverage test never finish.

**Comment by asciimoo** [comment]
No clue why

**Pull request merged**
