### PR TITLE
Doc installation corrections

### PR DESCRIPTION
**Pull request by return42**
## What does this PR do?

- add missing quotation marks in docs/build-templates
- searx configuration - add 'mkdir /etc/searx' before copy
- searx configuration - quote bash calls in sed replacements

This PR was inspired by #2273 & #2276 / thanks @pierrechtux

## How to test this PR locally?

    make docs

### CODE REVIEW

**Review by pierrechtux — COMMENTED** [review]
For some reason, when I run the
`make docs`
, the generated page
`searx/dist/docs/admin/installation-searx.html`
doesn't display correctly all the frames labeled 'bash'.

Therefore I cannot test the generated documentation.

I'm going to try to find out why that webpage is not correctly rendered, maybe something is wrong on my side.

**Comment by return42** [comment]
> doesn't display correctly all the frames labeled 'bash'.

Except the frame in chapter "Install packages" nearly all frames on this html-page do only have one tab and it is named "bash".

**Comment by pierrechtux** [comment]
> > doesn't display correctly all the frames labeled 'bash'.
> 
> Except the frame in chapter "Install packages" nearly all frames on this html-page do only have one tab and it is named "bash".

Yes, fine.  But in the html generated file on my machine, these frames do not appear at all.

Here is the output with the error messages when I try to regenerate the doc by making `make docs-clean docs`:

[searx_try_regen_documentation_2020_10_28__18_10.txt](https://github.com/searx/searx/files/5453688/searx_try_regen_documentation_2020_10_28__18_10.txt)

There's an error at the beginning concerning "missing command systemctl": this is normal, my machine runs on Devuan, which is basically a Debian without systemd.  This doesn't worry me much.

The two lines with "WARNING: Unexpected return code 42 from command " concerning "../utils/lxc.sh --help" and "../utils/searx.sh --help" worry me a bit more.

Sorry for the French in the output messages.

I'm trying to figure out how that system of documentation generation is working.

**Comment by return42** [comment]
> Sorry for the French in the output messages.

You can use `LANG=C` in front of your command to get `en` localized messages.

> Here is the output with the error messages when I try to regenerate the doc by making make docs-clean docs:

There is no need for `. ./searx-ve/bin/activate` when using Makefile targets, since they already build their own pyenv, see https://searx.github.io/searx/dev/makefile.html#python-environment

> my machine runs on Devuan, which is basically a Debian 

`make docs` should work

> a Debian without systemd

Our [installation scripts](https://searx.github.io/searx/admin/installation.html#installation-scripts) won't work.  I am not a fan boy of systemd but since all major distributors decided to pack systemd as default init system, all our installation scripts are using systemd.

**Comment by pierrechtux** [comment]
Here's the output, with `LANG=C`, of `make docs`.
[searx_try_regen_documentation_2020_10_30__15_12.txt](https://github.com/searx/searx/files/5465664/searx_try_regen_documentation_2020_10_30__15_12.txt)

Actually, the problem of those tabbed areas containing the code not appearing in the html files on my side is certainly related to my own setup, and doesn't have anything to do with your PR, so for the moment, I'll just leave it as it is.

(I initially thought that this would be a super-easy contribution... oh well... ;o))

**Review by pierrechtux — APPROVED** [review]
Seems good to me.  Too bad I cannot test, but this is most certainly my fault.

**Comment by return42** [comment]
> Too bad I cannot test, but this is most certainly my fault.

@pierrechtux thanks for taking the time!  _"don't worry, be happy"_ :smile:  ... if you wan't to have a last try I suggest to start from the beginning, very simply by::

````
$ cd ~/Downloads/
$ git clone https://github.com/searx/searx.git
$ cd searx/
$ git pull origin refs/pull/2277/head
$ SEARX_DEBUG=1 make docs-live
````

**Review by pierrechtux — APPROVED** [review]

**Comment by dalf** [comment]
Thank you !

**Comment by pierrechtux** [comment]
> @pierrechtux thanks for taking the time! _"don't worry, be happy"_ smile ... if you wan't to have a last try I suggest to start from the beginning, very simply by::
> 
> ```
> $ cd ~/Downloads/
> $ git clone https://github.com/searx/searx.git
> $ cd searx/
> $ git pull origin refs/pull/2277/head
> $ SEARX_DEBUG=1 make docs-live
> ```

I followed your advice, letter for letter (except I went to my favourite ~/tmp/ directory instead of Downloads), and still, I get the same results: no tabbed frames in the resulting webpage.

(not worth pasting here the long output from the make process, unless you wish to get it)

**Comment by return42** [comment]
> I followed your advice, letter for letter ... and still, I get the same results: no tabbed frames

That's really a pity / I do not have experience with Devuan so I can't say what's going wrong. I even do not know if it is related to Devuan or  what the cause is. Sorry that I can't help you solving the issue you have.

**Comment by pierrechtux** [comment]
No worries. Actually, Devuan is extremely similar to Debian, and my current setup is an actual Debian, which I switched to Devuan (that took just a few seconds).  I did that when the systemd made my machine boot in 30 minutes, instead of under one minute.

But I have another Debian machine closeby (which supports systemd), so I'll wake up that machine and I'll work on it, to check if this is related to Devuan or not.

**Comment by pierrechtux** [comment]
I've just tried that on a machine with Debian 10; results are even worse.

Some requirements are obviously missing: latex, something with pygments.

Here's a (long) record of my terminals when doing that:
[searx_try_regen_documentation_2020_11_05_20_09.txt](https://github.com/searx/searx/files/5496469/searx_try_regen_documentation_2020_11_05_20_09.txt)

Note that the text is structured with {{{ and }}} which are default delimiters for folding in vim.

In vim, setting:
```
set foldmethod=marker
set fdc=5
set foldclose=all
```
and playing with z commands helps a lot.

**Comment by return42** [comment]
> and playing with z commands helps a lot.

Use the terminal.

> get pull request from return42

This PR is already merged, no longer need to pull from my (old) branch.

> WARNING: Unexpected return code 42 from command '../utils/lxc.sh --help'

Its very hard to read this log from vim.  lxc is not needed to build the docs.

> ! LaTeX Error: File `anyfontsize.sty' not found.

Seems you have latex installed but something is missed .. if latex is installed, it is used to render math expressions.

> OSError: [Errno 98] Address already in use

The port docs-live uses is already used by another process.

Over all: the LOG looks very strange to me, never seen before.

Sorry, I can't help.

**Pull request merged**
