### PR TITLE
Adds Dogpile as an engine

### LINKED ISSUE #1196: Adding more search engines?
Hello,

I would like to add more search engines like.

One is similar to Gigablast, and some others might be Dogpile and Metacrawler, plus some others.

I know that I have to a new driver in:

searx/searx/engines/

searx/searx/settings.yml

but where else in SearX do I need to make changes?

Also, in the settings.yml there are engine designations like:

  - name : gigablast
    engine : gigablast
    shortcut : gb
    timeout : 3.0
    disabled: True

How is the "shortcut" designation determined and used?

Any help would be greatly appreciated.
Thanks

### PR DESCRIPTION
**Pull request by allendema**
## What does this PR do?
Adds Dogpile as an engine.

## Why is this change important?

Itself it uses Bing, but good to have it as a "proxy".
Vey similiar results to Qwant.

Quickly done with XPATH.

## Commands to run the tests or instructions to test the changes

Just do a seach with the engine, like so:
```
!dp streisand effect
```

## Author's checklist
Feel free to edit and improve this.

## Related issues

Partially closes #1196

### CODE REVIEW

**Review by kvch — APPROVED** [review]

**Comment by kvch** [comment]
@allendema Could you please fixup all the commits into a single one? Also, please rebase the PR.

**Comment by allendema** [comment]
> @allendema Could you please fixup all the commits into a single one? Also, please rebase the PR.

 Never done none of that but looks impossible from the Website IDE. o.O

**Comment by kvch** [comment]
I thought you could do it by `git rebase -i HEAD~4` and then change the last three`pick`s to `fixup`s. But if you cannot do it, I will squash the commit when merging.

**Comment by allendema** [comment]
> But if you cannot do it, I will squash the commit when merging.

Would you please do it, until I learn the real way?
Ty for your time!

**Pull request merged**
