### PR TITLE
Make german translation consistent

### PR DESCRIPTION
**Pull request by mdosch**
You use `Letzter Tag` and `Letzten Monat`. Both "letzter" and "letzten" are ok as you can read it as "Letzter Tag/Monat" or "[Den] letzten Tag/Monat" but you should not mix it.
I would prefer "Letzter".

### CODE REVIEW

**Review by 0xhtml — APPROVED** [review]

**Review by return42 — COMMENTED** [review]
Thanks!

**Review by return42 — APPROVED** [review]

**Comment by asciimoo** [comment]
Please fix the translations on Transifex it is synchronized with the repo before every release

**Comment by mdosch** [comment]
>Please fix the translations on Transifex it is synchronized with the 
Are you referring to me? If yes, please give me some time as I am busy 
right now and have to figure out transifex first.

**Comment by return42** [comment]
>  and have to figure out transifex first.

Same to me. @unixfox, you reacted with thumbs up, so I guess you know more about the Transifex workflow. The only thing I googled is a payed service which needs a login. I am completely at a loss, please give us a direction. / thanks!

**Comment by MarcAbonce** [comment]
It's this one: https://www.transifex.com/asciimoo/searx.

I just fixed this translation in Transifex, but yeah, the application not very intuitive to use at first in my opinion.

About the price, it's actually free for open source projects.

**Comment by mdosch** [comment]
Thank you 😃

**Comment by return42** [comment]
@MarcAbonce thanks a lot for this.  Did you know what the benefit is and how it is ..

> synchronized with the repo before every release

Sorry if my questions are stupid / I have never needed a account to implement or fix something.

**Comment by asciimoo** [comment]
> Sorry if my questions are stupid / I have never needed a account to implement or fix something.

Transifex has an interface what can be used by non-coders too, this is the primary reason why we use it.
I'm open to switch translation platform, if there are alternatives which don't require account.

**Comment by return42** [comment]
@asciimoo 

>  it is synchronized with the repo before every release.

how?

**Comment by asciimoo** [comment]
With this tool: https://pypi.org/project/transifex-client/

**Pull request closed without merging**
