### PR TITLE
[enh] update documentation about docker

### PR DESCRIPTION
**Pull request by dalf**
## What does this PR do?

* update the documentation about docker: https://asciimoo.github.io/searx/admin/installation-docker.html
* update the  dockerfiles/docker-entrypoint.sh  (the documentation call the script to get the help output)

## Why is this change important?

* the [wonderfall/searx](https://hub.docker.com/r/wonderfall/searx) image haven't been updated for a long time (but it is the case now, see related issue bellow).

## How to test this PR locally?

* ```make docs```: check the changes (feel free to correct my broken English)
* ```make docker``` : check the docker image works as intended.

## Related issues

* https://github.com/asciimoo/searx/issues/1779
* https://github.com/asciimoo/searx/issues/1561
* https://github.com/asciimoo/searx/issues/1785

### CODE REVIEW

**Review by asciimoo — APPROVED** [review]
Great, thanks!

**Comment by return42** [comment]
Strange, since 4a35975b42 the `make docs` hangs .. I guess it is [dockerfiles/docker-entrypoint.sh -h](https://github.com/asciimoo/searx/commit/4a35975b427b3ebee4f5cc54e2390356b0102536#diff-7ccaf381d47c8c2f3bd9ba8f5072baecR42) which hangs .. I do not have docker installed, could this the cause?

**Comment by dalf** [comment]
@return42 , there is no need to have docker (that's the point of the change in  dockerfiles/docker-entrypoint.sh : the script returns the help when it runs outside docker).

```make docs``` or ```make docs-live``` works fine in my setup.

**Comment by return42** [comment]
> make docs or make docs-live works fine in my setup.

Thanks for the info, then I have to check my setup.

**Comment by return42** [comment]
FYI: I updated gh-pages https://asciimoo.github.io/searx/admin/installation-docker.html

**Pull request merged**
