### PR TITLE
Python3: prevent crash when morty proxy is set

### LINKED ISSUE #1871: Python3: morty settings create hmac error
With python3 and morty proxy settings every query crashes:
```
  File "/usr/share/searx/searx/webapp.py", line 339, in image_proxify
    return proxify(url)
  File "/usr/share/searx/searx/webapp.py", line 321, in proxify
    hashlib.sha256).hexdigest()
  File "/usr/lib/python3.7/hmac.py", line 153, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3.7/hmac.py", line 49, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
```

and this looks like #968. Allready fixed it: patch follows.

### PR DESCRIPTION
**Pull request by cy8aer**
url_params['mortyhash'] needs a new hmac like in image_proxify. This
throws an error like in #968. Analog fixing with new_hmac like in #968

Fixes #1871.

### CODE REVIEW

**Review by kvch — DISMISSED** [review]

**Comment by return42** [comment]
Hi @cy8aer, sorry if asking dump questions .. I read through https://github.com/asciimoo/searx/issues/1871 but for me it is not clear if this PR is any longer needed ..

**Comment by cy8aer** [comment]
Am 20.04.20 um 15:02 schrieb Markus Heiser:
> Hi @cy8aer, sorry if asking dump questions .. I read through https://github.com/asciimoo/searx/issues/1871 but for me it is not clear if this PR is any longer needed ..
>
Hi Markus,

I am indifferent at that point:  I am running my instance now without
the patch and the !!binary entry as is described in the actual
documentation. But @dalf recommends more the non !!binary - and the
documentation is out of date.

I do not need it - !!binary works. This should be more the decision of
the maintainer -> @dalf.

Thomas

**Comment by return42** [comment]
> I do not need it - !!binary works. This should be more the decision of the maintainer 

@dalf what do you think, is this PR any longer needed?

**Comment by dalf** [comment]
Yes this can be close.
The documentation still need an update:
https://searx.github.io/searx/admin/morty.html

https://github.com/searx/searx/blame/master/docs/admin/morty.rst#L27
should be
`key : !!binary "your_morty_proxy_key"`

**Comment by return42** [comment]
> The documentation still need an update:

Ops .. I prepare a PR for.

**Pull request closed without merging**
