### PR TITLE
[enh] using typescript, improved map

### PR DESCRIPTION
**Pull request by pointhi**
### do not merge!

First, I would implement a good working big map
## 

I have rewrite the js-part inside the oscar-template to typescript. All is working like in the old script, but I have improved the code extensive.
- Autocompleter support POST-reqest
- much more modularisation
- some code improvements (for example: extensive use of jquery functions, to make the code smaller and more readable)

TODO:
- reimplement the big map with typescript (#217) **done**
- implement layer-control (should look like the ui from osm.org) **mostly done**
- implement routing  (#254)
- add menue which is shown if someone click on the map (show position, routing,...) **mostly done**
- search on the big map and display results **basic implementation done**
- parse geodata querys **parser done, visualisation is only done in a basic way**

### CODE REVIEW

**Comment by pointhi** [comment]
The current status of implementation can be viewed on https://searx.oe5tpo.com.

**Comment by ibrokemypie** [comment]
is the do not merge still relevant?

**Comment by pointhi** [comment]
I think yes.

The whole PR is running on my instance flawlessly: https://searx.oe5tpo.com, but there are still some open points and improvements to do.

**Comment by return42** [comment]
@pointhi is this PR any longer relevant?

**Comment by unixfox** [comment]
JavaScript is fine so I'm closing this issue.

**Pull request closed without merging**
