### PR TITLE
[fix] Update user agent versions

### PR DESCRIPTION
**Pull request by MarcAbonce**
DuckDuckGo is currently returning error on every query.
Updating the user agent to more recent versions seems to fix this.
I think this would also make #1303 redundant, since this is a cleaner version of the same fix.

### CODE REVIEW

**Comment by dalf** [comment]
Side note : there is #933 too.

**Comment by MarcAbonce** [comment]
I hadn't noticed that pull request. It would probably be better to merge that one instead.

**Review by asciimoo — APPROVED** [review]
Thanks!

**Comment by Pofilo** [comment]
Shouldn't we merge https://github.com/asciimoo/searx/pull/933 instead of this one ?

**Comment by asciimoo** [comment]
@Pofilo  it would be the futureproof solution, but there are still unresolved questions.

**Pull request merged**
