### PR TITLE
[enh] More data from Wikidata

### PR DESCRIPTION
**Pull request by MarcAbonce**
See #560

### CODE REVIEW

**Comment by dalf** [comment]
When there is more than one official website, there is a bug : there is one button "official website" with the contacted URLs.

Example : World of warcraft.

A different point : The links to YouTube, Twitter etc are not implemented, is it because these websites may / doesn't not respected privacy ? ( P2002,  P2013,   P2037,  P2003, ...)

**Comment by MarcAbonce** [comment]
Fixed!

About the social media links, I hadn't really thought about it, but I added them anyway. The user can choose whether or not to click those links, just like with normal search results here.

**Comment by dalf** [comment]
:-) 

Few more notes / requests : 
- the JSON format is not used so `%7Cwikitext` can be removed from `url_detail`
- the P18, P154 properties give a reference to an image.

Example, the wikidata page about [Linux](https://www.wikidata.org/wiki/Q388) contains :
https://commons.wikimedia.org/wiki/File:Tux.svg

the image link (png or jpg) is : 
https://commons.wikimedia.org/wiki/Special:FilePath/Tux.svg?width=200

width can be 200, 300, 500...

**Comment by dalf** [comment]
The more I spend time to understand / test the wikidata properties, the more I find...
@asciimoo may be merged and update after ?

Notes on current PR : 
- P2046 (area) may contains a list (for [Paris](https://www.wikidata.org/wiki/Q90) for example). I guess it can be the case for other properties. Not a big deal I guess.
- for the image perhaps get the logo and fall back to the image ( `['P154', 'P18', 'P242', 'P41', 'P2716', 'P2910']` ). For `Ubuntu` it seems more relevant for example. BTW the wikipedia engine replaces the image, and perhaps there is other example where the current implementation is better...

New things that could be nice (another PR ?) :
- the property [P402](https://www.wikidata.org/wiki/Property:P402) gives a number, which can be used to link directly to OSM this way : `https://www.openstreetmap.org/relation/{number}`. When this property is set, it can replace the OSM link where the zoom is most of time not set correctly.
- always about geocoordinate : [P1332](https://www.wikidata.org/wiki/Property:P1332), [P1333](https://www.wikidata.org/wiki/Property:P1333), [P1334](https://www.wikidata.org/wiki/Property:P1334) and [P1335](https://www.wikidata.org/wiki/Property:P1335) can be used to define the OSM link.
- the P242 (locator map image) or P15 (route map) give a link to a map. Useful for to have all the stops of a metro line (see [example for P15](https://www.wikidata.org/wiki/Q50761) and [example for P242](https://www.wikidata.org/wiki/Q19892) ). A link to this image could be nice, and second picture that the user can click would be great.

**Comment by MarcAbonce** [comment]
The infoboxes should now merge correctly.
Merging rows with ddg definitions works, but usually leads to some redundancy, such as "Birth" and "Date of birth" or "Creator" and "Created by". So I still left ddg disabled by default.

**Comment by MarcAbonce** [comment]
This PR should be ready to merge, btw.
There are probably still some things that could be tweaked, but these will only be found as more people use this feature.

**Comment by asciimoo** [comment]
great job! thanks

**Pull request merged**
