### PR TITLE
support time range search

### PR DESCRIPTION
**Pull request by kvch**
### Features (as requested in #383, #557)
- advanced search form under search input
- time range search
  - last day
  - last week
  - last month
- supported engines
  - Google
  - Yahoo
  - DuckDuckGo
  - Google Images
  - Deviantart
### Index page with Advanced settings closed

index
### Index page with Advanced settings open

index-advanced
### Search page with Advanced settings closed

search
### Search page with Advanced settings open

search-advanced
### Possible enhancements
- support more search engines
- search based on custom range
- add more settings to Advanced settings (e.g. safe search)

### CODE REVIEW

**Comment by dalf** [comment]
Great ! In the result page, would it be more clear if the categories and time range are displayed / expanded ?
[EDIT] Suggestion : Time range as a combo box which takes far less space. So the safe search, the search language / locale could all fit in the screen (to have a live example : duckduckgo does that).

**Comment by kvch** [comment]
@dalf What do you mean by displayed/expanded? Should the categories be shown always without clicking on advanced search?

When I created the UI my main goal was to be user-friendly, not compact. I'va read at a few pages that using "radiobuttons" are more user-friendly that using dropdowns. However, nearly all of the other search services use dropdowns to select time range. Those websites have (I suppose) UX teams with great knowledge, so it is wiser to follow their methods. Also, for users it would be much easier to adopt to searx if selecting the time range is similar to the widely-used alternatives. In a few days I'll push the redesign version with dropdowns. :) Thanks for your suggestion. :)

**Comment by dalf** [comment]
Yes, on the result page I think the categories / time range should be always displayed. I think the UX / UI should give a quick answer without click to the question "there are some results, but what was the request ?". By request I mean everything (text, time range, category, ... and language but that's another story)

It's not that the user will forgot what he has just entered, but he can adjust right away, leave the page and come back after, etc...

**Comment by asciimoo** [comment]
very-very awesome, thanks! =)

**Comment by 1xPdd** [comment]
The UI looks great! But, if I could, I'd really like to suggest (again) that dates should not be only measured as relative distance from the present as in last day/week/month. Library search engines and the likes allow dates to be limited to an arbitrary date range, as in from year to year. No general search engine that I know of does this. The advantage of a more flexible date adjustment is that it enables Searx to function as a tool for historical research. As to UI, it could be done via a slider or using a form.

**Comment by virtadpt** [comment]
Will this functionality be accessible from the search API?

**Comment by will76** [comment]
What about 'last year'? It's the best option to search for updated articles on a subject.

**Pull request merged**
