### PR TITLE
[enh] add plugin converting strings into hash digests

### PR DESCRIPTION
**Pull request by Venca24**

### CODE REVIEW

**Comment by kvch** [comment]
@Venca24 Could you please rebase your PR so we can merge it?

**Comment by Venca24** [comment]
I'll take a look on this on the weekend.

**Comment by Venca24** [comment]
Is it OK now?

I'm not just sure if the asciimoo's attribution in the plugin's file is done properly. I think I used the self info plugin as an example two years ago, but just it's basic structure is still there in the hash plugin.

**Review by kvch — APPROVED** [review]

**Comment by kvch** [comment]
Thank you!

**Pull request merged**
