### PR TITLE
Google Instant Answer results

### PR DESCRIPTION
**Pull request by nicholasks**
This will brings some updates to Google instant answers.

### CODE REVIEW

**Comment by ghost** [comment]
@asciimoo This is very useful !

**Comment by kvch** [comment]
Could you share an example query which demonstrates this addition? So far I haven't been able to see anything besides regular results from Google.

**Comment by dalf** [comment]
```recipe cookies``` for example will work in google and with this PR.
```age of barack obama``` won't be catched by this PR despite the google answer.

Actually a parser must be written for each answer type : recipe, age of..., actor of..., weather... 

Some links outside of the searx scope that may or may not provide a standalone solution aside of searx : 
* https://github.com/ayoungprogrammer/nlquery
* https://github.com/facebookresearch/DrQA
* https://docs.duckduckhack.com/

**Comment by return42** [comment]
I close this PR in favour of PR https://github.com/asciimoo/searx/pull/1985 / anyway I want to say; thanks a lot for your hints, which had its value in the google engine review!

**Pull request closed without merging**
