### PR TITLE
[fix] opensearch on chromium for android

### LINKED ISSUE #1666: Chromium-based browsers (Android) don't detect searx

### PR DESCRIPTION
**Pull request by unixfox**
## What does this PR do?

This PR set all the searches made by a Chrome/Chromium browser for Android to the "GET" method.

## Why is this change important?

In order to have Searx added a search engine on Chrome/Chromium for Android, the browser wants you to visit the correct specific URL `/?q=yourkeyword`.

## How to test this PR locally?

1. Run Searx locally
2. Install a chrome/chromium based browser on Android ([Bromite](https://www.bromite.org/) is a good choice).
3. Visit your Searx instance then make a search on it.
4. You should now see Searx in the "Recently visited" section of "Search engine" from the settings.
Screenshot_20200810-174631_Chromium_1_1

## Author's checklist

- I don't know how to allow the ability for the user to switch back to POST requests in the preferences. Maybe a developer that is used to the Searx code base could help me about that.
- I tested this PR on most of the popular browser and it doesn't break their opensearch discovery nor their search ability.
	- Microsoft Edge 15: [proof](https://i.imgur.com/vhCAkPF.png)
	- Microsoft Edge 84: [proof](https://i.imgur.com/EQE5C5c.png)
	- Google Chrome 84: [proof](https://i.imgur.com/4Mp81tZ.png)
	- Safari 13.1: [proof](https://i.imgur.com/pBVu1t9.png)
	- Firefox 79: [proof](https://i.imgur.com/xdS9O60.png)

## Related issues

Closes #1666

--------------------------

This PR is still a draft because I want to see if the maintainers and the contributors agree with my solution or if there is a better one.

### CODE REVIEW

**Comment by dalf** [comment]
I've tried:
* Chrome Desktop
* Chrome Android
* Firefox 79 desktop
* Firefox Android (build 2015757107)

All seems to work. 

---

I would move the check just after this line https://github.com/asciimoo/searx/blob/1eb00e0e717ff449ead9d49262a03cfbc4f7a53e/searx/webapp.py#L468
```python
    user_agent = request.headers.get('User-Agent', '').lower()
    if 'webkit' in user_agent and 'android' in user_agent:
        preferences.key_value_settings ['method'].value = 'GET'
```
(even if it seems to me to be a hack, the code should be in preferences.py)

---

> I don't know how to allow the ability for the user to switch back to POST requests in the preferences. Maybe a developer that is used to the Searx code base could help me about that

I don't think there is a reliable way to update opensearch.xml for now:
* either settings.yml has to be modified.
* [automatic update](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#Supporting_automatic_updates_for_OpenSearch_plugins) won't work since [cookies are not sent](https://github.com/asciimoo/searx/pull/2127#issuecomment-671077893)
* https://github.com/asciimoo/searx/issues/2069#issuecomment-671099077 can be a solution (not tested).

---

I understand the POST is not available on Chrom* browser. So actually the settings should be disabled in the preferences.

https://github.com/asciimoo/searx/blob/1eb00e0e717ff449ead9d49262a03cfbc4f7a53e/searx/templates/oscar/preferences.html#L77-L84

https://github.com/asciimoo/searx/blob/1eb00e0e717ff449ead9d49262a03cfbc4f7a53e/searx/templates/simple/preferences.html#L200-L209

I don't know how to implement that right now.

**Comment by unixfox** [comment]
> > I don't know how to allow the ability for the user to switch back to POST requests in the preferences. Maybe a developer that is used to the Searx code base could help me about that
> 
> I don't think there is a reliable way to update opensearch.xml for now:
> 
>     * either settings.yml has to be modified.
> 
>     * [automatic update](https://developer.mozilla.org/en-US/docs/Web/OpenSearch#Supporting_automatic_updates_for_OpenSearch_plugins) won't work since [cookies are not sent](https://github.com/asciimoo/searx/pull/2127#issuecomment-671077893)
> 
>     * [#2069 (comment)](https://github.com/asciimoo/searx/issues/2069#issuecomment-671099077) can be a solution (not tested).
> 
> 
> I understand the POST is not available on Chrom* browser. So actually the settings should be disabled in the preferences.
> 
> https://github.com/asciimoo/searx/blob/1eb00e0e717ff449ead9d49262a03cfbc4f7a53e/searx/templates/oscar/preferences.html#L77-L84
> 
> https://github.com/asciimoo/searx/blob/1eb00e0e717ff449ead9d49262a03cfbc4f7a53e/searx/templates/simple/preferences.html#L200-L209
> 
> I don't know how to implement that right now.

~~I wasn't talking about the method for the opensearch but more about the method used in the search bar on Searx home page.~~
~~How do I make it so the user can still switch back to POST requests in this search bar by changing the method in the preferences?~~
~~image~~

~~The summary is that I would like to force the GET method only if the user didn't change the method in the preferences.~~

**EDIT**: Moving the code to https://github.com/asciimoo/searx/blob/1eb00e0e717ff449ead9d49262a03cfbc4f7a53e/searx/webapp.py#L468 solved my question.

Also, I don't think we should disable the method preference because what if like I said earlier the user wants to do manual searches (from the Searx home page) in POST?

**Comment by asciimoo** [comment]
> I understand the POST is not available on Chrom* browser. So actually the settings should be disabled in the preferences.

A minor correction: POST is available on chrome if the search query is submitted from the search form and if the url isn't the same as the url in the opensearch.xml

**Comment by dalf** [comment]
LGTM.

---

If we want to be clean about the code:

in webapp.py:
```python
user_agent = request.headers.get('User-Agent', '').lower()
preferences = Preferences(themes, list(categories.keys()), engines, plugins, user_agent)
```

in preferences.py, before https://github.com/asciimoo/searx/blob/093dd42bb05feafb2cc77304d3b1a9a1a3016949/searx/preferences.py#L324

```python
default_method = 'POST'
if 'webkit' in user_agent and 'android' in user_agent:
    default_method = 'GET'
```
then replace this line https://github.com/asciimoo/searx/blob/093dd42bb05feafb2cc77304d3b1a9a1a3016949/searx/preferences.py#L351 by
```python
settings['server'].get('method', default_method),
```

Then all the calls to the Preferences constructor must be updated :
* tests/unit/test_search.py
   * with a FF user agent
   * add a test with a Chrome Android user agent, check the method is GET instead of POST.
* utils/standalone_searx.py
   * add a fake user agent.

**Review by dalf — APPROVED** [review]

**Comment by dalf** [comment]
Thank you

**Comment by unixfox** [comment]
@dalf Didn't you want to have a cleaner implementation based on what you suggested here: https://github.com/asciimoo/searx/pull/2132#issuecomment-672780292?

**Comment by dalf** [comment]
@unixfox it would be better / cleaner, but the current implementation is simple enough, so I have merged the PR.

[EDIT] My wish is to merge some PR before a freeze period because of the "Drop Python 2" PR.

**Pull request merged**
