### PR TITLE
Added rumble.com video search engine.

### PR DESCRIPTION
**Pull request by datagram1**
New video search engine: rumble.com
Added rumble.py to searx/engines/
Add rumble.com to sears/settings.yml -1254
Same style + xpath processing using lxml as other engines.
No changes anywhere else.

### CODE REVIEW

**Comment by unixfox** [comment]
Please disable the engine by default and fix the checks

**Comment by return42** [comment]
`make test.pep8` fails: https://github.com/searx/searx/pull/2588/checks?check_run_id=1936565783#step:7:36

Before send PR please run

     make test

Have a look at [quickstart guide](https://searx.github.io/searx/dev/quickstart.html) more info available at [How to contribute](https://searx.github.io/searx/dev/contribution_guide.html)

**Comment by datagram1** [comment]
looks good now

**Comment by unixfox** [comment]
Please squash your commits into one.

**Comment by datagram1** [comment]
commits squashed into 1

**Pull request merged**
