### PR TITLE
Remove hubsbpot tracking URL params

### PR DESCRIPTION
**Pull request by 3nprob**
## What does this PR do?

Removes hubspot tracking parameters from result URLS

### CODE REVIEW

**Comment by return42** [comment]
Can you give me some example (queries) at hand? .. who is using *hubspot*? / thanks

**Comment by 3nprob** [comment]
https://knowledge.hubspot.com/settings/how-do-i-create-a-tracking-url
https://knowledge.hubspot.com/ads/ad-tracking-in-hubspot
https://knowledge.hubspot.com/ctas/calls-to-action-frequently-asked-questions

example query: `b! site:thelancet.com  hsenc`

**Comment by 3nprob** [comment]
Digging up those links I found a couple of parameters I missed with a SE post to boot

https://meta.stackexchange.com/questions/263392/what-are-these-very-long-parameters-in-so-careers-feedback-always-welcome-url

**Review by return42 — DISMISSED** [review]
Works like a charme / thanks a lot!

One nit I have; do you like to add the links from the comment:

> https://knowledge.hubspot.com/settings/how-do-i-create-a-tracking-url
> https://knowledge.hubspot.com/ads/ad-tracking-in-hubspot
> https://knowledge.hubspot.com/ctas/calls-to-action-frequently-asked-questions

to the commit message?  This will help later, when others want to maintain the regular expressions.

**Comment by kvch** [comment]
Once the comments above are addressed, it is ready to be merged. Also, while you are rewording the commit message, please rebase the branch on top of master.

**Comment by 3nprob** [comment]
Roger that! Just pushed

**Review by kvch — APPROVED** [review]

**Comment by kvch** [comment]
@3nprob Thank you!

**Pull request merged**
