### PR TITLE
[enh] update translations

### PR DESCRIPTION
**Pull request by pointhi**
I updated the translations on transifex. There was a bug #221, so I copied the strings for categories manually from older files. Now, all should be up-to-date on transifex.

### CODE REVIEW

**Comment by asciimoo** [comment]
Thanks! Could you add the hebrew translations too?

**Comment by asciimoo** [comment]
\o/ thanks! Now @GreenLunar can start the testing of #214

**Comment by GreenLunar** [comment]
Looks good!

Where do you want me to report on RTL bugs?

**Comment by Cqoicebordel** [comment]
You have already the open issue #214 :)

**Pull request merged**
