### PR TITLE
flake8

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
- all errors are ignored. future pr can try to fix it with pep8 error
- because requirements-dev.txt is not sorted, the flake8 package is put on top
- ~only `searx/static/themes` is ignored, searx and example folder should be checked (unlike pep8 check)~
- test is limited to some folder and setup file, also`searx/static/themes` is ignored because generated python file

related #1674

e: update test target

### CODE REVIEW

**Comment by dalf** [comment]
It would be better to only include the directories to check, otherwise the exclude list might be long.
Example of directory that doom flake8: node_modules, the virtual env directory.

Note sure if 
```
flake8 --ignore "E117 E211 E231 E302 E305 E402 E501 E722 F401 F632 F811 F821 F841 W291 W391 W503 W504 W605" --exclude "$SEARX_DIR/static/themes" searx tests
```
is okay ?

**Comment by rachmadaniHaryono** [comment]
i just made change as your suggestion

as note here are failed file/folder:
```
searx/__init__.py
searx/answerers/statistics/answerer.py
searx/engines
searx/plugins/__init__.py
searx/plugins/https_rewrite.py
searx/query.py
searx/results.py
searx/search.py
searx/utils.py
searx/webapp.py
setup.py
tests/test_robot.py
tests/unit/engines/test_btdigg.py
tests/unit/engines/test_currency_convert.py
tests/unit/engines/test_duden.py
tests/unit/engines/test_google_images.py
tests/unit/engines/test_seedpeer.py
tests/unit/test_preferences.py
utils/fetch_currencies.py
utils/fetch_firefox_version.py
utils/fetch_languages.py
utils/google_search.py
utils/standalone_searx.py
```
e: as for the long line of the ignored error, it is unavoidable for now and because flake8 is stricter than pep8

**Comment by return42** [comment]
FWIW: pylint is a part of the boilerplate see (don't bookmark) https://return42.github.io/searx/dev/makefile.html#make-pylint

I really prefer to conditioning the [.pylintrc](https://github.com/asciimoo/searx/blob/master/.pylintrc) file so that it becomes a quality gate one day .. and replaces the pep8.

**Comment by rachmadaniHaryono** [comment]
if it is agreed and pylint will replace this pr i'm okay with that and will close this pr 

i actually wait months for response

**Comment by return42** [comment]
> if it is agreed and pylint will replace this pr i'm okay with that and will close this pr

no, it is not agreed .. pylint its just a alternative I do prefer (help me to detect errors where code coverage fails).  Please let this PR open.

> i actually wait months for response

Thats true and I am very sorry about .. please take into mind, that we are all have a payed job .. we invest a lot of time on searx .. I am new here at searx, other do this since years .. we have so many PRs open ... that was the reason why I asked to help on searx .. now I am here and I will do my best .. but we need more much resources anyway.

/ thanks for your patience.

**Comment by rachmadaniHaryono** [comment]
actually i'm glad it is active now, even if i didn't use it as often as before.

just ping me if something need to be done with my pr or issue

**Comment by return42** [comment]
We are gonig to check more and more python modules with pylint / https://github.com/searx/searx/blob/master/Makefile#L216

I close this PR.

**Pull request closed without merging**
