### PR TITLE
Remove cache of Dockerfile

### PR DESCRIPTION
**Pull request by jjasonkal**
- Decrease size of the image by removing cache of pip upgrade.

### CODE REVIEW

**Comment by unixfox** [comment]
Is it really necessary when there is `--no-cache` for every apk command?

**Comment by jjasonkal** [comment]
It removes 3MB so there are still some cache of the upgrade and apk. @unixfox

**Comment by unixfox** [comment]
Can you prove that by using [dive](https://github.com/wagoodman/dive) for example?

**Comment by jjasonkal** [comment]
I checked it and `pip3 install --upgrade pip` leaves 3MB of cache behind. @unixfox

**Comment by dalf** [comment]
I confirm:

dive-searx-searx

There is a /root/.cache/pip directory using either ```pip3 install --no-cache``` or ```pip3 install --no-cache-dir```.

With ```pip3 install --no-cache-dir --upgrade pip``` , the /root/.cache/pip directory is smaller but still exist.

**Review by dalf — DISMISSED** [review]

**Comment by unixfox** [comment]
Before merging the changes: would it be better to combine the two commits into one?

**Comment by dalf** [comment]
Anything against "squash and merge" ?

**Comment by jjasonkal** [comment]
Thanks you, I have just combined them in one.

**Review by dalf — APPROVED** [review]

**Pull request merged**
