### PR TITLE
Feature/parse obfuscated google

### LINKED ISSUE #1596: Google results not working everytime
I just experienced a recent bug where Google sometimes is trying to load his new UI even if JavaScript is not activated. This make Searx not finding any results because it can't parse the new UI:

Here is the saved HTML page generated by Google when it tries reply with his new UI:

And the old UI that Searx can parse without any issue:

To resolve this bug I had the idea to force the user agent to Internet Explorer 12 by adding:
````python
params['headers']['user-agent'] = "Mozilla / 5.0(MSIE 12.0; Trident / 7.0; rv: 11.0) like Gecko"
````
I tried that trick and it worked everytime because Google know by default that it can't load his new UI on IE.

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
this handle new google ui if old parse don't give any result

fix #1596 

test against html given from @unixfox

~~yaml dump from `results` variable~~

yaml below is outdated, see output yaml on comment below

https://github.com/asciimoo/searx/pull/1603#issuecomment-506217958

```yaml
- {content: "Your source for entertainment\nnews, celebrities, celeb news, and celebrity\
    \ gossip\u200B. Check out the\nhottest fashion, photos, movies and TV shows!",
  title: E! News, url: 'https://www.eonline.com/'}
- {content: 'E! Watch later. Share. 7:42. 0:00 / 7:42.', title: E! Entertainment -
    YouTube, url: 'https://www.youtube.com/channel/UCj7V_ikJOXO9RC8at6kYfHQ'}
- {content: "Welcome to the E! News YouTube Channel.\u200B ... From latest celebrity\
    \ and pop culture news to freshest E! Original series on Youtube, the E! News\
    \ Youtube Channel is the #1 place to get the scoop.\u200B ... Join Will Marfuggi,\
    \ Melanie Bromley and E! News correspondents as they discuss the hottest pop ...",
  title: E! News - YouTube, url: 'https://www.youtube.com/channel/UCjDsbbzHgTrGc4Ff26TJtsA'}
- {content: '', title: '"Keeping Up With the Kardashians" Katch-Up S14, EP.6 | E!
    - YouTube', url: 'https://www.youtube.com/watch?v=u4GoS0-R9Sg'}
- {content: 'E! (an initialism for Entertainment Television) is an American pay television
    channel that is owned by the NBCUniversal Cable Entertainment Group division of
    NBCUniversal, all owned by Comcast.', title: E! - Wikipedia, url: 'https://en.wikipedia.org/wiki/E!'}
- {content: 'Wil je online spelen? Ontdek de e-games van de Nationale Loterij Win
    for Life, Presto, Subito, Cash, 21, Spaarpot Smash, SuperSafe, Rabbits Run.',
  title: E-games Nationale Loterij - Online Spelen - e-lotto.be, url: 'https://www.e-lotto.be/NL/eGames'}
- {content: 'Th!nk E presents its activities in the field of smart energy, smart grids,
    smart buildings and EU projects.', title: Th!nk E, url: 'https://www.think-e.be/'}
```

### CODE REVIEW

**Comment by unixfox** [comment]
I don't know if you saw my review: https://github.com/asciimoo/searx/pull/1603/files/481b0de121bc4519530143633d299e52060836f1

If #1597 gets merged should it be reverted if your PR works perfectly with the new UI?

**Comment by rachmadaniHaryono** [comment]
i did but unfortunately this is only tested against your html file data and i can't guarantee if this will work perfectly.

imo it is better if user agent set as default config on settings.yaml and with that searx only use default parser with non obfuscated html.

anyone else who want to use this can disable that user agent config on their settings.yaml and use this parser

**Comment by unixfox** [comment]
ok I tough you tested your PR with a real Searx instance before creating it.

> imo it is better if user agent set as default config on settings.yaml and with that searx only use default parser with non obfuscated html.
anyone else who want to use this can disable that user agent config on their settings.yaml and use this parser

Sure but that would require an additional work to introduce a way to customize the user agent in the settings.yml because currently it's not possible to completely replace the default user agent with a newer one. It's only possible to add a contact email address after the default user agent.

I mean if you fix the bug that I left in the review, then if everything work why not reverting my PR #1597 and apply your PR by default for Google?

**Comment by rachmadaniHaryono** [comment]
>ok I tough you tested your PR with a real Searx instance before creating it.

i did and i use it on my fork. but i just don't create another test other than your html files

>Sure but that would require an additional work to introduce a way to customize the user agent in the settings.yml because currently it's not possible to completely replace the default user agent with a newer one. It's only possible to add a contact email address after the default user agent.

yeah you are right, because after i look it once again and it kinda challenging to add another key to it

from what i see you have add another key e.g. `user_agent` to `query_engines` variable on `get_search_query_from_webapp` function on `search` module. that way you can just replace default user agent on `Search.search` method 

e:

>I mean if you fix the bug that I left in the review, then if everything work why not reverting my PR #1597 and apply your PR by default for Google?

this parser may not work. it may work most of the time on my machine, but it can broken when google change their html structure

**Comment by rachmadaniHaryono** [comment]
the new commit taking fixes from #1628 as comparison

new yaml output

```yaml
- content: "Your source for entertainment\nnews, celebrities, celeb news, and celebrity\
    \ gossip\u200B. Check out the\nhottest fashion, photos, movies and TV shows!"
  title: E! News
  url: https://www.eonline.com/
- content: E! Watch later. Share. 7:42. 0:00 / 7:42.
  title: E! Entertainment - YouTube
  url: https://www.youtube.com/channel/UCj7V_ikJOXO9RC8at6kYfHQ
- content: "Welcome to the E! News YouTube Channel.\u200B ... From latest celebrity\
    \ and pop culture news to freshest E! Original series on Youtube, the E! News\
    \ Youtube Channel is the #1 place to get the scoop.\u200B ... Join Will Marfuggi,\
    \ Melanie Bromley and E! News correspondents as they discuss the hottest pop ..."
  title: E! News - YouTube
  url: https://www.youtube.com/channel/UCjDsbbzHgTrGc4Ff26TJtsA
- content: "05 Nov 2017 \xB7 The family travels to Cleveland to support Tristan during\
    \ one of his big games.\u200B Plus, Kourtney ...Duration: 2:27 Posted: 05 Nov\
    \ 2017"
  title: '"Keeping Up With the Kardashians" Katch-Up S14, EP.6 | E! - YouTube'
  url: https://www.youtube.com/watch?v=u4GoS0-R9Sg
- content: E! (an initialism for Entertainment Television) is an American pay television
    channel that is owned by the NBCUniversal Cable Entertainment Group division of
    NBCUniversal, all owned by Comcast.
  title: E! - Wikipedia
  url: https://en.wikipedia.org/wiki/E!
- content: Wil je online spelen? Ontdek de e-games van de Nationale Loterij Win for
    Life, Presto, Subito, Cash, 21, Spaarpot Smash, SuperSafe, Rabbits Run.
  title: E-games Nationale Loterij - Online Spelen - e-lotto.be
  url: https://www.e-lotto.be/NL/eGames
- content: Th!nk E presents its activities in the field of smart energy, smart grids,
    smart buildings and EU projects.
  title: Th!nk E
  url: https://www.think-e.be/
```

**Comment by return42** [comment]
This PR does not / no longer work. Lets close this PR unmerged and switch to https://github.com/asciimoo/searx/pull/1628 which is much more straight forward.  BTW the old UI is dead and the code parsing old UI can be dropped.

**Pull request closed without merging**
