### PR TITLE
Update public_instances.rst

### PR DESCRIPTION
**Pull request by darkwarrior3**
Added searx I2P (Invisible Internet Project) instance

### CODE REVIEW

**Comment by return42** [comment]
Thanks for your contrib .. and sorry for nitpicking you, but can you please use [good commit messages](https://asciimoo.github.io/searx/dev/contribution_guide.html#code). The other thing I want to ask for: please add a blank line between title and first para.

Beside this bikeshedding I have some question (not familiar with I2P):

Should we add a note, that the link needs I2P layer installed? .. should we add links with common installation instructions? ...

**Review by return42 — COMMENTED** [review]
please use [good commit messages](https://asciimoo.github.io/searx/dev/contribution_guide.html#code)

**Comment by unixfox** [comment]
@darkwarrior3 You won't be able to change the commit message from the web interface Github.com. You will need to [clone your forked Github repository of Searx](https://github.com/darkwarrior3/searx) then switch to `patch-1` branch with `git checkout patch-1` then change the commit message using [this guide](https://help.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message).
I hope this helps if you didn't use the git command line until now.

**Comment by unixfox** [comment]
@darkwarrior3 
If you want to get this pull request merged you will have to stop using the GitHub web interface and learn the `git` command.
I see you are still making commits with bad names even though I explained to you how to do the proper way.

**Review by darkwarrior3 — COMMENTED** [review]
Updating public_instances.rst : i) Added searx for I2P section.
ii) Added searx installation(official site) and Wikipedia link (For more info because I2P isn't famous.)
iii) Added 2 searx instances I2P link send

**Comment by darkwarrior3** [comment]
> @darkwarrior3
> If you want to get this pull request merged you will have to stop using the GitHub web interface and learn the `git` command.
> I see you are still making commits with bad names even though I explained to you how to do the proper way.

Is it right?

**Comment by unixfox** [comment]
No it isn't, look at the commit messages.
First thing there are 4 commits instead of one.
Second thing, the commit messages doesn't explain the changes.

**Comment by darkwarrior3** [comment]
> No it isn't, look at the commit messages.
> First thing there are 4 commits intead of one.
> Second thing, the commit messages doesn't explain the changes.

Ah fine. I'll do it tomorrow. Night here.

**Comment by return42** [comment]
Sorry, a minimal SCM & git knowledge is needed to contribute.

**Pull request closed without merging**
