### PR TITLE
devianart: use RSS API, etc.

### PR DESCRIPTION
**Pull request by Yetangitu**
use RSS API, add 'content', 'img_format' and 'source' (these two need PR #1567 to be displayed), 'author' fields, use biggest thumbnail image available

### CODE REVIEW

**Comment by Yetangitu** [comment]
BTW, pep8 might choke on the unit test which contains long lines. May I suggest turning off that check, at least for unit tests? As it is now it just creates extra work for something which many already see as extra work, i.e. extra extra work. In this case the unit test contains long RSS lines as that is what the Deviantart backend returns and as such is what the code should be tested with.

```
$ pip install pycodestyle
$ pycodestyle ...

  '\n\n'
/srv/searx/tests/unit/engines/test_deviantart.py:38:121: E501 line too long (181 > 120 characters)
/srv/searx/tests/unit/engines/test_deviantart.py:49:121: E501 line too long (138 > 120 characters)
/srv/searx/tests/unit/engines/test_deviantart.py:50:121: E501 line too long (125 > 120 characters)
```

**Comment by Yetangitu** [comment]
This is what the result should look like (with PR #1567 applied)

image

**Comment by kvch** [comment]
@Yetangitu To solve the issue of too long lines put `# noqa` to the end of the line. This is what we do in case of tests with long lines.

**Comment by dalf** [comment]
There are encoding problem with the DeviantArt API, see : 
https://github.com/DeviantArt/DeviantArt-API/issues/157

**Comment by return42** [comment]
@Yetangitu  @dalf do you know the state of this PR .. should we merge? If so, @Yetangitu would you please update to current branch master and solve conflicts? / Thanks a lot!

**Comment by Yetangitu** [comment]
I'll update if it is to be merged, using the local version without problems here.

**Comment by return42** [comment]
> I'll update if it is to be merged, using the local version without problems here.

There are conflicts which needs to be solved before one can test this PR.

**Comment by dalf** [comment]
See https://github.com/searx/searx/pull/2286

**Pull request closed without merging**
