### PR TITLE
 plugin: generic_url_rewrite 

### LINKED ISSUE #2609: Capability to rewrite hits url
**Is your feature request related to a problem? Please describe.**
Not related to a problem with `searx`, per se. I am looking to have `searx` rewrite the hits urls to another domain. 

**Describe the solution you'd like**

For example, if my results have a few urls from `www.reddit.com`, I'd like to have those rewitten to `old.reddit.com`.  If you could point me to where to start looking at, I'd be glad to send a PR if I am successful. My apologies if this already exists - if so, please guide how to accomplish this. 

In `settings.yml`, a section to include plain domain rewrites
<pre>
www.reddit.com: old.reddit.com
www1.domain.com: www3.domain.com
old.foo.org: new.foo.org
</pre>
**Describe alternatives you've considered**

Currently, I go to the address bar and perform manual rewrites. It would be great if `searx` can do the rewrites for me instead.  
**Additional context**

Sometimes, you'd want to access a specific endpoint for a results URI.

### PR DESCRIPTION
**Pull request by anmathew**
## What does this PR do?
Adds a new plugin <b>generic_url_rewrite</b> that allows to rewrite hits url. 

## Why is this change important?
A new plugin, as we discussed in https://github.com/searx/searx/issues/2609 

As encouraged by @unixfox and mentored by @dalf in  https://github.com/searx/searx/issues/2609#issuecomment-791746428, I am sending this PR. 

## How to test this PR locally?

Edit file `plugins/genericRewrites/config.yml` and add a test entry as 
<pre>
www.reddit.com: old.reddit.com
</pre>
And enable the plugin from `Preferences`.
Then perform a search for `reddit searx` - the output urls should be rewritten to `old.reddit.com` 

## Author's checklist
Tested locally on my lxc machine, 

Please feel free to tweak, if you'd like. 
## Related issues
Closes #2609

### CODE REVIEW

**Comment by unixfox** [comment]
Could you squash your commits?

**Comment by anmathew** [comment]
> Could you squash your commits?
Please check now.

**Comment by unixfox** [comment]
No squashing is not that. I mean merging all your commits into one.

**Comment by anmathew** [comment]
> No squashing is not that. I mean merging all your commits into one.

Well, then let me send in another PR, easier that way!

**Comment by anmathew** [comment]
Sending in https://github.com/searx/searx/pull/2638

**Comment by unixfox** [comment]
> > No squashing is not that. I mean merging all your commits into one.
> 
> Well, then let me send in another PR, easier that way! 

No please don't. You can do it without creating another PR.

Look for "squash commits into one" on your search engine and you will find some help about it.

**Comment by return42** [comment]
Please do not flood PRs and before push changes to remotes check your code using `make tests`.  Read [quickstart guide](https://searx.github.io/searx/dev/quickstart.html) and [How to contribute](https://searx.github.io/searx/dev/contribution_guide.html) and since you are working with git, teach yourself some git basics.

**Pull request closed without merging**
