### PR TITLE
Add cloudron as installation method

### PR DESCRIPTION
**Pull request by gramakri**
Hi Searx team, we have been maintaining Searx package for Cloudron for a while now. Can it be added as an alternate install method for searx? The source code for the package is here - https://git.cloudron.io/cloudron/searx-app .  We also have some automated selenium tests which help us update searx easily - https://git.cloudron.io/cloudron/searx-app/-/tree/master/test . If anything in the manifest or listing (https://cloudron.io/store/io.github.ascimoo.searx.html) requires changes, please let me know.

Thanks!

### CODE REVIEW

**Comment by return42** [comment]
Thanks for using searx. Im not the owner I'm just a contributor like others here. I can't speak for others, these are my personal thoughts.

I see two problems, the first problem is, that we do not have control over that image. I personally do not want to promote a fork over which I do not have control.  The second problem I see: I have no problem with using open source commercially, but I also think, that the searx project itself is not the right place to promote (or prefer) "this or that" commercial project.

Lets hear what other say.

**Comment by HLFH** [comment]
I support @return42 viewpoint as I am not in favor of supporting searx with non-standard packaging that is not mainstream. Selfhosting and protecting your own personal data can be done the standard way. 

This commit contains content that is written like an advertisement.

The only thing you can do at the time is to add your own searx public instance: https://github.com/dalf/searx-instances
With [morty](https://github.com/asciimoo/morty) and [filtron](https://github.com/asciimoo/filtron).
Regarding filtron, I prefer the alternative [antibot-proxy](https://github.com/unixfox/antibot-proxy).
And implement [searx-checker](https://github.com/searx/searx-checker) with the right nginx config.
So you can be on the searx instances statistics website: https://searx.space/.

**Comment by gramakri** [comment]
@return42 @HLFH OK. Thanks for considering. Our intent is not to just advertise. On the contrary, we have maintained this package for over a year and written selenium tests specific to searx as well. So, a lot of work has gone into this package and we haven't come and spammed your issue tracker :). Just wanted to point that out. Thanks again.

**Comment by return42** [comment]
@gramakri Over years and with great effort, many contributors have created a product with which others can earn money. The contributors do not expect any benefit of any kind for their efforts :). Just wanted to point that out. Thanks again

**Pull request closed without merging**
