### PR TITLE
mymemory_translated: fix python 3 support

### LINKED ISSUE #2023: mymemory_translated engine: unexpected crash 'str' object has no attribute 'decode'
mymemory engine does not work.
You can see it in the search engine statistics: https://searx.space/#.

Either: "unexpected crash 'str' object has no attribute 'decode'"
Or: "no result"

My instance is https://searx.hlfh.space (I use antibot-proxy) and I have the first issue.
I am using mymemory with the API key I got from the service.

### PR DESCRIPTION
**Pull request by HLFH**
## What does this PR do?

This PR fixes the python 3 support for search engine mymemory_translated: https://github.com/asciimoo/searx/issues/2023

[dictzone.py](https://github.com/asciimoo/searx/blob/master/searx/engines/dictzone.py) engine had quite some similar fixes.

Closes #2023

### CODE REVIEW

**Comment by HLFH** [comment]
@return42 @dalf Don't hesitate to review :)

**Review by asciimoo — APPROVED** [review]
Great, thanks!

**Comment by asciimoo** [comment]
I hope it isn't problem that I did the review. =]

**Comment by HLFH** [comment]
@asciimoo 

**That was a quick review**


**I am impressed**


Thank you!

**Comment by return42** [comment]
> @return42 @dalf Don't hesitate to review :)

@HLFH sorry .. I had no chance :)

ani

**Pull request merged**
