### PR TITLE
[enh] fix content fetching, parse published date from description for startpage and ixquick

### PR DESCRIPTION
**Pull request by pointhi**
I fixed the broken description parsing for startpage and ixquick, and furthermore added parsing of publishedDate (which is embedded in the description).

### CODE REVIEW

**Comment by Cqoicebordel** [comment]
(there is no commit for ixquick. Is that wanted ?)

**Comment by pointhi** [comment]
ixquick and startpage using the same engine, and also the same layout (I think it's the same company)

**Comment by Cqoicebordel** [comment]
Sorry, jumped the gun a bit too quickly ;)

**Comment by asciimoo** [comment]
@pointhi, great, thanks! =)

**Pull request merged**
