### PR TITLE
[Engine] add npm search engine

### PR DESCRIPTION
**Pull request by jfowl**
I often used DuckDuckGos !npm bang, now I would love to have it integrated into searx.

### CODE REVIEW

**Comment by kvch** [comment]
Great contribution! However, do as I see the responses are in JSON format. Do you mind refactoring it as a JSON engine? Here is an example: https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L424

**Comment by jfowl** [comment]
Just as a note for me, to implement it later:
```
  - name : npm
    engine : json_engine
    paging : True
    search_url : https://api.npms.io/v2/search?q={query}&size=25&from={pageno}
    results_query : results
    url_query : package/links/npm
    title_query : package/name
    content_query : package/description
    page_size : 25
    categories : it
    shortcut : npm
```

**Comment by jfowl** [comment]
@kvch Could you review & merge this soonish, I kinda messed up my git history (still getting used to git collaboration) and would like to have a blank new plate for integrating some other fixes :)

**Comment by dalf** [comment]
Thank you!

**Pull request merged**
