### PR TITLE
unit tests

### PR DESCRIPTION
**Pull request by Cqoicebordel**
Let's continue...

### CODE REVIEW

**Comment by asciimoo** [comment]
=))
<3
Seems, the currency convert try/except block isn't necessary.

**Comment by Cqoicebordel** [comment]
I thought so, but wasn't sure. The other float() had also a try/except so I thought it was mandatory.
Anyway, I will delete it tomorrow. Thanks !

**Comment by Cqoicebordel** [comment]
I think I'm done here for now.

What is left is either engines that don't work anymore or is out of my depth, I think. Maybe I will try to tackle them, but not right now. If anyone want to do it, you are welcome to.

So, @asciimoo you can merge :)

**Comment by asciimoo** [comment]
very-very cool, thanks again!

**Pull request merged**
