### PR TITLE
Add engine for Emojipedia

### PR DESCRIPTION
**Pull request by obfuscated-loop**
## What does this PR do?
This adds an [Emojipedia](https://emojipedia.org/) engine to searX, making it easy to find whatever emoji you want under a certain search term.

## Why is this change important?
Emojis are commonly used for various types of expression, and aren't language specific. The problem is that not all systems have a place to search for an exact emoji - or even copy them. This is where Emojipedia comes in; it's essentially a Wikipedia of different emojis, which also, showcases how the emojis will look on different systems.

By using it as an engine within searX, you can copy from the direct search result or visit the page to learn more about the emoji as summarised.

## How to test this PR locally?
`!em person`
This should return a search result including emojis with people in them.

### CODE REVIEW

**Comment by kvch** [comment]
@james-still Do you mind fixing the error in the Python 3.9 job?

**Comment by obfuscated-loop** [comment]
> @james-still Do you mind fixing the error in the Python 3.9 job?

Sorry for the late response. Just made the commit.

**Comment by kvch** [comment]
I've tested the engine with the example query you provided, but I get no results back. Am I missing something?

**Comment by obfuscated-loop** [comment]
> I've tested the engine with the example query you provided, but I get no results back. Am I missing something?

That's odd, maybe try a different query like 'math' - as you can see it's been merged into searXNG and seems to be working fine.

**Comment by obfuscated-loop** [comment]
I think they might have updated their site and it's affecting the xPath values. I'll have a closer look in an hour.

**Comment by obfuscated-loop** [comment]
All working now but leave it unmerged. I'll implement a relative xPath tonight so this doesn't happen again.

**Comment by obfuscated-loop** [comment]
Should be good to merge now by the way :+1:

**Comment by kvch** [comment]
Thank you!

**Review by kvch — APPROVED** [review]

**Pull request merged**
