### PR TITLE
[fix] remove usage of request context where not available

### LINKED ISSUE #1920: Unhandled expection when engine times out
The following exception occurs when an engine does not respond in time returning a timeout error.

```
Exception in thread aeb1ee8b-0fe7-4e90-8f29-0c487673c1eb:
Traceback (most recent call last):
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/home/n/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/n/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/n/.pyenv/versions/3.6.3/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/n/.pyenv/versions/3.6.3/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 326, in recv_into
    raise timeout("The read operation timed out")
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='gitlab.com', port=443): Read timed out. (read timeout=1.0)

During handling of the above exception, another exception occurred:


Traceback (most recent call last):
  File "/home/n/p/searx/searx/search.py", line 160, in search_one_http_request_safe
    search_results = search_one_http_request(engine, query, request_params)
  File "/home/n/p/searx/searx/search.py", line 93, in search_one_http_request
    response = send_http_request(engine, request_params)
  File "/home/n/p/searx/searx/search.py", line 77, in send_http_request
    return req(request_params['url'], **request_args)
  File "/home/n/p/searx/searx/poolrequests.py", line 133, in get
    return request('get', url, **kwargs)
  File "/home/n/p/searx/searx/poolrequests.py", line 109, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='gitlab.com', port=443): Read timed out. (read timeout=1.0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/n/.pyenv/versions/3.6.3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/n/.pyenv/versions/3.6.3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/n/p/searx/searx/search.py", line 107, in search_one_request_safe
    return search_one_http_request_safe(engine_name, query, request_params, result_container, start_time, timeout_limit)
  File "/home/n/p/searx/searx/search.py", line 189, in search_one_http_request_safe
    result_container.add_unresponsive_engine((engine_name, gettext('timeout')))
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/flask_babel/__init__.py", line 548, in gettext
    t = get_translations()
  File "searx/webapp.py", line 168, in _get_translations
    translation_locale = request.form.get('use-translation')
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/n/p/searx/venv3.6/lib/python3.6/site-packages/flask/globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

@dalf has already provided a patch to fix it: https://github.com/asciimoo/searx/pull/1903#issuecomment-607137470

### PR DESCRIPTION
**Pull request by kvch**
@dalf I have prepared an alternative fix to the exception. The problem was that `_get_translations` tried to use a request object where it was not available. But it was not necessary to use a request context to set up a translation. It could be done in `get_locales` where we actually learn which locale should be used.

@MarcAbonce Could you please review the PR?

Closes #1920

### CODE REVIEW

**Comment by MarcAbonce** [comment]
This fixes the exception, but it causes another bug. If any user sets their locale to Occitan, everybody else will get their content in Occitan as well because `occitan_loaded` is a global state.

One way I could solve this in my localhost is just by validating the request context at the top of the monkey-patched `_get_translations`, similar to how it's done in [flask_babel's version](https://github.com/python-babel/flask-babel/blob/master/flask_babel/__init__.py#L202) at the very beginning.

**Comment by kvch** [comment]
@MarcAbonce I've fixed the fixed based on your hints. Thanks for the review.

**Review by MarcAbonce — DISMISSED** [review]

**Comment by dalf** [comment]
No more exception but the the three error messages in search.py are translated into French instead of Occitan when the interface language is Occitan :

| English           | Occitan               | French            |
|-------------------|-----------------------|-------------------|
| timeout           | relambi passat<br>    | délai dépassé<br> |
| request exception | excepcion de requèsta | erreur de requête |
| unexpected crash  | fracàs pas previst    | crash inattendu   |

It makes sense since ```has_request_context()``` is False in the threads started by search.py

**Comment by kvch** [comment]
@dalf Yes, it is true. However, the issue you see is unrelated to this PR. I suggest we move forward with this fix as it eliminates the exception it is supposed to.

**Comment by dalf** [comment]
In my opinion:
* Before this PR ```translation_locale = request.form.get('use-translation')``` raises an exception : missing request context.
* With this PR, the wrong translation is picked because the request context is missing.

So I really feel the two issues are related.

[This patch](https://github.com/asciimoo/searx/pull/1903#issuecomment-607233994) solves the two issues.
In addition, only the UI ( webapp.py ) import babel, and the search.py removes this import.

May be I missing a point, or you see another implementation, so feel free to merge since as you said it removes the exception.

**Comment by kvch** [comment]
For the record, the issue is present on the current master branch as well. It was not introduced by this PR. My goal was to get rid of the exception, and it's done by this PR.

I am OK with adding your patch to this PR. My intention with treating issues separately is to keep PRs small and easy to understand so we can iterate on the code more quickly.

**Comment by kvch** [comment]
@dalf I've added addressed the engine error translation issue in this PR. It is similar to your patch.

**Comment by kvch** [comment]
And now I've pushed the changes...

**Review by dalf — APPROVED** [review]

**Comment by dalf** [comment]
> My intention with treating issues separately is to keep PRs small and easy to understand so we can iterate on the code more quickly.

I agree:
* one solution is to fix the exception: the Occitan language choice doesn't crash, but it doesn't work as expected (before it was crashing).
* another solution is to fix the Occitan language choice (and the PR title is still right: removes  usage of request context).

I felt the additional changes were small enough to be included, but it's a matter of taste. I'm okay with smaller PR.

I've checked the PR everything seems to work as expected.

**Comment by kvch** [comment]
@dalf Thank you for the review and testing! It helped a lot.

**Pull request merged**
