### PR TITLE
Implement #1209

### PR DESCRIPTION
**Pull request by dalf**
Implement #1209 :
- settings.yml has the same format as before
- doi.yml, locales.yml and engines.yml are loaded before (the disabled attributes are removed)
- if yaml search.engines path is defined, then all engines are disabled, and only engine specified in this list are enabled.
- settings.yml contans only general, search, server, ui sections. The search section contains the enabled engines.
- settings_robot.yml is unchanged

### CODE REVIEW

**Comment by dalf** [comment]
Some notes : 
* In this implementation an administrator can't define its own engine. I think that "search.engines_yaml" and "search.include_engines_yaml" should be added in settings.yml. The first one to replace engines.yml path, the second to add another engines.yml.
* May be doi.yml, locales.yml, and engines.yml should be moved to the same directory than currencies.json and engines_languages.json ?

**Comment by dalf** [comment]
Add two new settings : 
* search.engines_path : path of engines.yml
* search.include_engines_path : additional engine definitions (doesn't replace the content of engines.yml)
    
doi.yml, engines.yml, locales.yml are loaded directly into doi, engines, locales (not more prefix). Avoid to have settings about engines inside doi.yml for example. 

Note that the DOI settings have changed.

Some bug fixes on oa_doi_rewrite.

**Comment by jfowl** [comment]
What do the core contributers think about this? I think this is a very smart idea all in all.

**Comment by asciimoo** [comment]
Separating the engines part of the settings is a good idea, but the other files (languages, doi) aren't really necessary. What is the advantage of spreading the settings to multiple small files?

**Comment by dalf** [comment]
Replaced by #2291

**Pull request closed without merging**
