### PR TITLE
startpage and ixquick enignes : disabled by default, and timeout set to 6 seconds.

### LINKED ISSUE #329: Startpage engine broken
There is no result when I'm using the bang "!startpage"

### PR DESCRIPTION
**Pull request by dalf**
Fix #329

### CODE REVIEW

**Comment by asciimoo** [comment]
Totally agree with disabling both by default, they are quite slow and unstable, but the 6sec default timeout isn't too much? It can cause three times slower responses in general category if one of these enabled. Personally i don't really like longer responses than 3sec.
Another alternative is a preferences option to set the timeout parameter individually (for each engine?).

**Comment by dalf** [comment]
6 sec is based on the average response time I saw on searx.me. It's average so there is slower time!  

If the engine is disabled by default, I think the use case is to enable it using a bang, and in this case, 6 sec is long but it is better than no result. I forgot the other use case : enable the engine.

Some option about the time out are perhaps a solution, but this PR is quick & dirty fix that resolved the global response time, and try to make those two engines usable. Purpose : release a 0.8.0 version without referenced bugs.

**Comment by asciimoo** [comment]
You can enable them from the preferences too and there is no sign or warning about the significant response time increase which can be confusing - and i know, timeout and no results are confusing too.. =)

**Comment by dalf** [comment]
Ok, so let's switch back to 3 seconds ?

**Comment by asciimoo** [comment]
Overall i think it would be better at first.
devs?

**Comment by Cqoicebordel** [comment]
I think the 6sec + disabled was a good quick and dirty fix.

But yes, we need more :
- Being able to set the timeout in the prefs (with a bit of info about latency)
- Having a tiny note indicating what search engines timeouted on the result page

And yes @asciimoo you are right too. We can't distribute a version which has this kind of issue (-> no warning of the big latency if enabled)

**Comment by asciimoo** [comment]
@Cqoicebordel yes, a small notification or a box on the right side with the engine timeouts would be useful too!

**Comment by dalf** [comment]
Another idea : why set a time out when there is only one engine ? If the engine take time to respond, then searx also, but since there is nothing else to show, it's not issue.

So why not change the time out behaviour : 
- if there is only one engine : set the time out to 60 seconds (yes, because there is a connection pool, so if the user send a lot of requests they will have an end )
- if there is more than one engine : normal time out behaviour.

**Comment by Cqoicebordel** [comment]
That could work too, but I'm afraid that the user will refresh the page sooner that the timeout, and so, resending the request, and reseting the timeout to 0 each time, keeping himself away from the results.

**Comment by dalf** [comment]
see #343

**Comment by asciimoo** [comment]
Nice solution @dalf! Thanks!

**Comment by asciimoo** [comment]
ah, sry, i merged my local branch, but it's in the master: aac8d3a7bfdd77a5369e52a4ece99b20669a4625
closing

**Pull request closed without merging**
