### PR TITLE
Fix engine spotify

### PR DESCRIPTION
**Pull request by 0xhtml**
The spotify API requires authentication with API credentials.

### CODE REVIEW

**Comment by return42** [comment]
Hi @finn0 .. thanks for your PR and sorry for the late response .. we (maintainers) are all busy :o 

> The spotify API requires authentication with API credentials.

Does the old API without authentication no longer exists or is there no longer a way to crawl spotify without account?

I rellay like to test your PR .. Is there any chance to test spotify engine without account?

**Comment by 0xhtml** [comment]
As you can read here https://developer.spotify.com/documentation/web-api/#authentication all requests to the spotify api require authentication. You can not test the api without credentials.

**Comment by return42** [comment]
> all requests to the spotify api require authentication. You can not test the api without credentials.

Thanks for clarifying .. with this information we do not have any regression (It can only get better ) and I merge PR even without explicit testing the spotify engine.

**Review by return42 — APPROVED** [review]
Thanks!

**Comment by HLFH** [comment]
I am getting the error: ERROR:searx.engines:Missing engine config attribute: "spotify.api_client_id"
searx is no longer starting correctly.

**Comment by unixfox** [comment]
Just comment the engine like in the default settings.yml and everything will be fine.

**Comment by return42** [comment]
Spotify needs API credentials / see 

- https://github.com/asciimoo/searx/pull/1661#issuecomment-569436131
- https://github.com/asciimoo/searx/blob/master/searx/settings.yml#L603

**Comment by HLFH** [comment]
You can create a client_id from here: https://developer.spotify.com/dashboard/login

In /etc/searx.conf, adding the related `api_client_id` & `api_client_secret` fixed it.

**Pull request merged**
