### PR TITLE
[fix] url bar autocomplete (opensearch suggestions)

### PR DESCRIPTION
**Pull request by return42**
**test clients needed:** To test, you can add the search engine from https://darmarit.org to your browser, activate _Search Suggestions_ and set this search engine for suggestions.  If you need a link direct to the OpenSearch-XML, use this one: https://darmarit.org/searx/opensearch.xml

Note: Instance at https://darmarit.org has #2656 and #2716 installed.

----

Since #2593 is merged the OpenSearch-Format is buggy.  The loop in [1] will
change raw_text_query object and this will change also the value of
`raw_text_query.query` on every `raw_text_query.changeQuery(result)`.

This patch fixes this issue by storing the initial query value in `sug_prefix`.

[1] https://github.com/searx/searx/blob/ac0fdc3b9670168de8061ed0e656dd66a567d741/searx/webapp.py#L804-L806

OpenSearch-Format::

    [ "<query>",
      [ "<term 1>", "<term 2>", ... "<term n>" ],
      [ "<content 1>", "<content 2>", ..., "<content n>" ],
      [ "<url 1>", "<url 2>", ..., "<url n>" ]
    ]

- https://www.google.com/support/enterprise/static/gsa/docs/admin/current/gsa_doc_set/xml_reference/query_suggestion.html#1080002
- https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Supporting_search_suggestions_in_search_plugins#implementing_search_suggestion_support_on_the_server

Legacy-Format::

    [ "<term 1>", "<term 2>", ..., "<term n>" ]

- https://www.google.com/support/enterprise/static/gsa/docs/admin/current/gsa_doc_set/xml_reference/query_suggestion.html#1081079

----

Requires: https://github.com/searx/searx/pull/2656

### CODE REVIEW

**Comment by BBaoVanC** [comment]
Yesterday I reverted #2656 on my searx instance, but this PR still seems to work.

**Comment by return42** [comment]
> Yesterday I reverted #2656 on my searx instance, but this PR still seems to work.

Thanks for the info .. is your searx behind a HTTPS proxy, did you removed the searx from your browser's search engine list and added it again?

For me #2656 fixes a issue with the opensearch.xml behind a HTTPS  proxy, that was the reason why I mentioned #2656 as a prerequisite.

**Review by unixfox — APPROVED** [review]
Thank you Markus for your contribution.

I just tested in a local Searx installation and it works fine.

This PR can be merged in order to restore the capability of autocomplete in the search bar.

**Comment by BBaoVanC** [comment]
> > Yesterday I reverted #2656 on my searx instance, but this PR still seems to work.
> 
> Thanks for the info .. is your searx behind a HTTPS proxy, 

I have it behind Filtron like in the official public instance instructions.

> did you removed the searx from your browser's search engine list and added it again?
>
> For me #2656 fixes a issue with the opensearch.xml behind a HTTPS proxy, that was the reason why I mentioned #2656 as a prerequisite.

Yes, that's what I had to do for the suggestions to start working again.

**Comment by return42** [comment]
> I have it behind Filtron like in the official public instance instructions.

Thanks for the info. To narrow down the cause for my problems (for which I need  #2656) I have additional questions .. I would like to make sure:  Your Instance is HTTPS, right?  

> Yes, that's what I had to do for the suggestions to start working again.

You first reverted  #2656 and after this you reinstalled searx to you browsers search engine list .. right?

And my last question is: do you have a path in your URL like https://example.org/searx or is your URL https://example.org

**Comment by BBaoVanC** [comment]
> > I have it behind Filtron like in the official public instance instructions.
> 
> Thanks for the info. To narrow down the cause for my problems (for which I need #2656) I have additional questions .. I would like to make sure: Your Instance is HTTPS, right?

Yeah, I have nginx with a reverse proxy to Filtron, which has a reverse proxy to searx itself. Everything is regular HTTP, until it gets to nginx, which is exposed to the outside world.

> 
> > Yes, that's what I had to do for the suggestions to start working again.
> 
> You first reverted #2656 and after this you reinstalled searx to you browsers search engine list .. right?

Yeah, I also just removed it and readded it, and it still works. Just to make sure, I made a branch named [merge_2716_and_revert_2656](https://github.com/BBaoVanC/searx/tree/merge_2716_and_revert_2656) which is based on the official searx master branch (not my fork), and it still works. Looking at the opensearch.xml when testing locally, I see these two lines:

```xml
<Url rel="suggestions" type="application/x-suggestions+json" template="http://127.0.0.1:8888/autocompleter?q={searchTerms}"/>
<Url type="application/opensearchdescription+xml" rel="self" template="/opensearch.xml?method=POST&autocomplete=duckduckgo"/>
```

If I checkout this branch on my public instance and look at its opensearch.xml, I see pretty much the same:

```xml
<Url rel="suggestions" type="application/x-suggestions+json" template="https://search.bbaovanc.com/autocompleter?q={searchTerms}"/>
<Url type="application/opensearchdescription+xml" rel="self" template="/opensearch.xml?method=POST&autocomplete=duckduckgo"/>
```

I also see the same two lines in the opensearch.xml on my fork's [branch with all my custom modifications](https://github.com/BBaoVanC/searx/tree/revert-2656).

> 
> And my last question is: do you have a path in your URL like https://example.org/searx or is your URL https://example.org

My url is just https://search.bbaovanc.com/ with no path.

**Comment by return42** [comment]
@BBaoVanC Thanks a lot for your feedback that helped me better narrow down the error.

In PR #2760 I fixed the issues we have with PR #2656 (no need to rollback). I discussed this topic with @avpnusr, if you are interested in have a look at  https://github.com/searx/searx/issues/2740#issuecomment-817824919 and the following comments.

If you have time, do you like to check if PR #2760 fixes your issues you had with PR #2656?

If you do so, lets continue this discussion in PR #2760.

**Comment by unixfox** [comment]
@kvch can you take a look at this PR?

**Comment by unixfox** [comment]
@return42 why did you close this PR?

**Comment by BBaoVanC** [comment]
They closed #2760 too for some reason

**Comment by return42** [comment]
> why did you close this PR?
>  ...closed #2760 too for some reason

@BBaoVanC @unixfox / sorry, github did close PR  #2760 and #2716 when I made some house housekeeping in my repository.  Maintainers should be able to restore the branch (and reopen PR).

**Comment by return42** [comment]
FYI: restored branch

**Review by BBaoVanC — APPROVED** [review]

**Pull request merged**
