### PR TITLE
[enh] implement simple spell checker as plugin, FIX #189

### LINKED ISSUE #189: detect spelling error using provided suggestions
currently, we are recive suggestions from a few search-engines, but the strings are containing most time more as the actual search query (what suggestions should). But this suggestions have the correct spelling, even if the query is wrong. So I think we should use that suggestions, to check the query for spelling errors, and displaying a spelling-correction on the result-page if required.

For example, using the [Damerau–Levenshtein distance algorithm](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance) which is a fast spelling-correction algorithm as described in the faroo-blog (http://blog.faroo.com/2012/06/07/improved-edit-distance-based-spelling-correction).

Furthermore, a searx-instance can build an index which is containing all word from received suggestions, so the spelling-correction is also working for image-search,... as soon as the word is used with an engine with is providing suggestions

### PR DESCRIPTION
**Pull request by pointhi**
it's the same spellchecker like in the pull-request #190, but implemented as plugin and without usage of a defined wordlist.

Fixing issue: #189

### CODE REVIEW

**Comment by asciimoo** [comment]
Could you add some tests, to demonstrate the usage/efficiency/performance?

**Comment by asciimoo** [comment]
Sorry for the long-long delay, I reviewed the code at last.
The functionality is ok, but it doesn't fit to the current plugin system. Implements custom variables/functionality in templates and webapp. Two possible solutions:
- Improve the plugin system and templating
- Rewrite it as a standard preferences option which is really easy since the user settings refactor

**Comment by pointhi** [comment]
hm, the thing why I changed some implementation in the webapp and template was because I added a new field in the template specific for such data. I'm not sure how to achive this in another way.

At least, we could extend the current template system to be able to add custom variables easily, but nevertheless it's somehow required to change the template to parse this new datasets.

**Comment by asciimoo** [comment]
I understand the purpose of the modifications, it is just out of a plugins scope. Yes, we can extend the template system to handle these cases, but i think it's easier and less effort to rewrite the pr as a standard preferences option like the autocompleter.

**Comment by ibrokemypie** [comment]
personally i think extending the scope of plugins to useful functionality like this would be much better than just adding them as features. independently developed plugins could add to the growth without adding bloat, plugins being independant to each instances choice.

**Comment by return42** [comment]
@pointhi is this PR any longer relevant?

**Comment by return42** [comment]
no feedback, I guess we can close this PR.

**Comment by return42** [comment]
@unixfox lets close this PR / thanks!

**Pull request closed without merging**
