### PR TITLE
Revise of the gigablast engine

### PR DESCRIPTION
**Pull request by return42**
The gigablast API has changed and seems to have some quirks, this is the first
revise.  More work (hacks) are needed.

### CODE REVIEW

**Comment by return42** [comment]
FWIW: gigablast fails in so many ways ...

- totally broken API; mostly ignores "number of results per query" and randomly interpretation of "first result number" (pagination is complete broken, not only in the API, also in the WEB client)
- totally broken HTTP service: https://observatory.mozilla.org/analyze/gigablast.com
- missing SSL and redirects from the official link https://www.gigablast.com
- do not live up to their own claim (["The Google Contradiction", Feb 20, 2020](https://www.gigablast.com/blog.html#metaloss))

**Comment by return42** [comment]
FYI: also merged into the [searx-next branch](https://github.com/return42/searx/tree/searx-next)

- [searx-next instance](https://darmarit.org/searx)
- [searx-next docs](https://return42.github.io/searx/)
- [searx-next merged PRs](https://github.com/return42/searx/projects/1)

test: [!gb corona](https://darmarit.org/searx/?q=%21gb%20corona)

**Comment by HLFH** [comment]
So many diffs. Does this PR fix https://github.com/asciimoo/searx/pull/1966?
yahoo engine is not working. You added a comment (https://github.com/asciimoo/searx/pull/1961#issuecomment-635484390), but you then redirected to this PR.

**Comment by return42** [comment]
> So many diffs.

?

> Does this PR fix https://github.com/asciimoo/searx/pull/1966?
yahoo engine is not working. 

No!  PR #1974 is about GIGABLAST

> You added a comment (https://github.com/asciimoo/searx/pull/1961#issuecomment-635484390), but you then redirected to this PR.

In that comment I wrote, that #1961 is about GIGABLAST but in its patch series is a YAHOO patch (see https://github.com/asciimoo/searx/pull/1961/commits).

In the next coment https://github.com/asciimoo/searx/pull/1961#issuecomment-635490207 I closed #1961 in favor of this PR #1974.

In short: the mess starts in #1961 .. I closed this PR, forget all about!

**Review by dalf — APPROVED** [review]
@return42, I let you merge.

**Pull request merged**
