### PR TITLE
Add TVmaze engine

### PR DESCRIPTION
**Pull request by liimee**
## What does this PR do?

Add tvmaze (show search) engine

## Why is this change important?

I think a tv show search would be a great addition

## How to test this PR locally?

- `make run`
- search `!tm test`

### CODE REVIEW

**Comment by kvch** [comment]
I wonder if this engine could be simplified to be a `json_engine` in `settings.yml`. Have you tried that?
Example:
```yaml
 - name : openairepublications
   engine : json_engine
   paging : True
   search_url : https://api.openaire.eu/search/publications?format=json&page={pageno}&size=10&title={query}
   results_query : response/results/result
   url_query : metadata/oaf:entity/oaf:result/children/instance/webresource/url/$
   title_query : metadata/oaf:entity/oaf:result/title/$
   content_query : metadata/oaf:entity/oaf:result/description/$
   content_html_to_text: True
   categories : science
   shortcut : oap
   timeout: 5.0
   about:
     website: https://www.openaire.eu/
     wikidata_id: Q25106053
     official_api_documentation: https://api.openaire.eu/
     use_official_api: false
     require_api_key: false
     results: JSON

```

**Comment by liimee** [comment]
I tried doing this:
```yml
- name : tvmaze
  engine : json_engine
  search_url : https://api.tvmaze.com/search/shows?q={query}
  url_query : show/url
  title_query : show/name
  content_query : show/summary
  content_html_to_text : True
  timeout: 5.0
  shortcut : tm
  about:
    website: https://www.tvmaze.com/
    wikidata_id: Q84863617
    official_api_documentation: https://www.tvmaze.com/api
    use_official_api: True
    require_api_key: False
    results: JSON
```
but it didn't return the right titles:
tvm

**Comment by unixfox** [comment]
I think this engine should be disabled by default too.

**Comment by kvch** [comment]
JSON engine seems to match everything under `show/name`, even `show/country/name`, etc. We will fix it a follow up PR, and take yours in until it is fixed. Thanks!

**Review by kvch — APPROVED** [review]

**Pull request merged**
