### PR TITLE
add digbt engine - fixes #638

### LINKED ISSUE #638: with KAT being targeted, could we get digbt search working as a backup?
I predict this wont be the last we here about torrent sites being targeted and after KAT domain seizure i believe the mirrors might get targeted as well. could searx get http://www.digbt.org/ as a backup since btdigg is also down

### PR DESCRIPTION
**Pull request by kvch**
Introduce new XPATH engine digbt.org based on request in #638.

### CODE REVIEW

**Comment by dalf** [comment]
:-)

I don't know how to keep the xpath engine to add information about magnet, upload, download.
That's really help to choose the right torrent.

**Comment by kvch** [comment]
TODO (so nothing will be forgotten in conenction with this PR)
- [ ] refactor XPATH engine so it can support torrent results
- [ ] let digbt use the refactored XPATH engine

**Comment by kvch** [comment]
I did not refactor the XPATH engine, because I did not want to pollute it with torrent related codes. So I moved digbt into a seperate engine. I did a small refactor: calculation of sizes of torrents were moved to utils to avoid code duplication.

**Comment by asciimoo** [comment]
thanks

**Pull request merged**
