### PR TITLE
[enh] Load modules from settings file

### PR DESCRIPTION
**Pull request by milouse**
This pull request is an attempt to answer #778.

### CODE REVIEW

**Comment by milouse** [comment]
rebased on master

**Review by bouckdarko — DISMISSED** [review]

**Comment by return42** [comment]
Can you implement an else-path if profile is not in settings file?  We need this for downward compatibility .. see https://asciimoo.github.io/searx/dev/install/installation.html#how-to-update

**Comment by milouse** [comment]
I've just rebased on master and provide backward compatibility by adding the old imports in an else statement.

**Comment by return42** [comment]
Tested but got problems.  Go to Preferences -> Plugins .. The names of the plugins are not shown, instead the variable name e.g. `oa_doi_rewrite` is shown as plugin title.

**Comment by milouse** [comment]
Whoops, didn't see that. My last commit fix that (I directly use importlib instead of the searx wrapper).

**Comment by return42** [comment]
Just want to add a cross link to https://github.com/asciimoo/searx/pull/1938 https://github.com/asciimoo/searx/pull/1613

**Comment by kvch** [comment]
Closing as the feature has been implemented in commit a05c660. Thank you for your contribution anyway. If the current feature on master is not what you are looking for, feel free to open an issue.

**Pull request closed without merging**
