### PR TITLE
Fix google image search engine

### PR DESCRIPTION
**Pull request by Nachtalb**
Fix google image search error

Because there is not full image url in the dom, I replaced "image_url" with the same url as the "url" (url of the source).
See example HTML https://gist.github.com/Nachtalb/2dea8a4d2c723c49226ad9645838121f

before
---
image

after
---
image

### CODE REVIEW

**Comment by dalf** [comment]
Thank you. 
Could you squash all the commits in one ?

More over, it seems the "safe" parameter values are : 
* ```active``` : to enable safe search
* ```images``` : to disable safe search

(from https://www.google.com/advanced_image_search form)

**Comment by Nachtalb** [comment]
> More over, it seems the "safe" parameter values are

I'll do that

> Could you squash all the commits in one?

I have seen this in other PR's too but I don't get why you would want to do this. A commit is normally supposed to contain only one specific change and not a whole bunch. That is what merging and so on is for. Don't get me wrong, I will do it, it is your Repo after all and so your rules count. I'd just like to know why 😄

**Comment by Nachtalb** [comment]
I now pushed the squashed commits including the safe search value update.

**Comment by Yetangitu** [comment]
See PR #1566  - Google does return JSON which contains all data needed to get to the full image. They also return the full page title, the original image dimensions and more.

**Comment by Yetangitu** [comment]
BTW, a good way to see what Google returns - and with that find a way to scrape those results - is by using `curl`, `xidel` and `jq` to run these queries on the command line:

Use `curl` to see the raw results:

```
$ curl -s --user-agent 'Mozilla/5.0 (X11; Linux i686; rv:60.0) Gecko/20100101 Firefox/60.0' 'https://www.google.com/search?q=searx+meta+search+engine&tbm=isch&yv=2&start=0&ijn=0'

<div eid="qRuzXPDHD4e-6ASVsz0" style="display:none"><div data-cei="qRuzXPDHD4e-6ASVsz0" class="rg_add_chunk"> ...(lots of HTML elided)... </a><div class="rg_meta notranslate">{"id":"s-RgFBmtg7FI7M:","isu":"en.wikipedia.org","itg":0,"ity":"png","oh":996,"ou":"https://upload.wikimedia.org/wikipedia/commons/3/35/Screenshot-2017-8-31_searx_me.png","ow":1920,"pt":"Searx - Wikipedia","rh":"en.wikipedia.org","rid":"aQY0Y3TQsYSZMM","rt":0,"ru":"https://en.wikipedia.org/wiki/Searx","s":"","sc":1,"st":"Wikipedia" ...
```

use `xidel` to filter out these results to pure JSON, possibly followed by `jq` to pretty-print that JSON:

```
$ xidel --user-agent 'Mozilla/5.0 (X11; Linux i686; rv:60.0) Gecko/20100101 Firefox/60.0' 'https://www.google.com/search?q=searx+meta+search+engine&tbm=isch&start=0&ijn=0&yv=2' --extract '//div[@data-ved]//div[contains(@class, "rg_meta")]/text()'|jq '.'|head -25
**** Retrieving (GET): https://www.google.com/search?q=searx+meta+search+engine&tbm=isch&start=0&ijn=0&yv=2 ****
**** Processing: https://www.google.com/search?q=searx+meta+search+engine&tbm=isch&start=0&ijn=0&yv=2 ****
{
  "id": "s-RgFBmtg7FI7M:",
  "isu": "en.wikipedia.org",
  "itg": 0,
  "ity": "png",
  "oh": 996,
  "ou": "https://upload.wikimedia.org/wikipedia/commons/3/35/Screenshot-2017-8-31_searx_me.png",
  "ow": 1920,
  "pt": "Searx - Wikipedia",
  "rh": "en.wikipedia.org",
  "rid": "aQY0Y3TQsYSZMM",
  "rt": 0,
  "ru": "https://en.wikipedia.org/wiki/Searx",
  "s": "",
  "sc": 1,
  "st": "Wikipedia",
  "th": 162,
  "tu": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwY1OrQCiAB5yDfYzIpkMtADiCCaG5Wxk-SxstHf9Ht84D87Jr",
  "tw": 312
}
{
  "cb": 18,
  "cl": 6,
  "cr": 6,
  "ct": 9,
```

**Comment by Yetangitu** [comment]
...and yes, the user agent DOES make a big difference in deciding what data is returned. Set it to something unknown and Google returns 'old-style' data (without JSON), set it to a known CLI tool (e.g. `curl`) and Google will not return any data. To get JSON results the user agent *must* be set to a known browser.

**Comment by dalf** [comment]
A [random user agent](https://github.com/asciimoo/searx/blob/master/searx/data/useragents.json) is used for the each searx request (useragents.json can be updated with a [sript](https://github.com/asciimoo/searx/blob/master/utils/fetch_firefox_version.py)).

The difference I see are about the parameters : 
* yv=2&ijn=0 is the PR #1566 (the browser asks to download the partial document). 
* gbv=1&sa=G is this PR (full HTML document).

**Review by dalf — APPROVED** [review]
Thank you

**Comment by dalf** [comment]
To avoid waiting each other while the google image engine doesn't work, I merge this PR.
@yetangitu can you update your PR.

**Comment by Yetangitu** [comment]
I can update it in such a way as to undo the changes this PR does since it ignores the (better) JSON data available (e.g. full image path, etc).

**Comment by Nachtalb** [comment]
@Yetangitu Thanks 👍 for the clarification and updating your branch!

**Comment by dalf** [comment]
@Yetangitu  : yes.

**Comment by Yetangitu** [comment]
> A [random user agent](https://github.com/asciimoo/searx/blob/master/searx/data/useragents.json) is used for the each searx request (useragents.json can be updated with a [sript](https://github.com/asciimoo/searx/blob/master/utils/fetch_firefox_version.py)).
> 
> The difference I see are about the parameters :
> 
>     * yv=2&ijn=0 is the PR #1566 (the browser asks to download the partial document).

This depends on the user agent parameter. With an unknown or 'old' browser you'll get an HTML document without JSON, with a 'modern' browser it'll feed you HTML with embedded JSON. The user agents defined in `searx/data/useragents.json` are 'modern' enough to get JSON. Try it on a command line to see what Google returns without interference from browsers prompting about partial documents etc, you'll notice it returns a single `<div>` with more `div`s embedded, amongst them the one containing the JSON data: `<div class="rg_meta notranslate">{....}`.

Maybe the first xpath selector (on `//div[@data-ved]`) can be removed as it seems to be superfluous, the only thing extracted from it is another xpath (`./div[contains(@class, "rg_meta")]/text()`)

**Pull request merged**
