### PR TITLE
Fix typo virualenv

### PR DESCRIPTION
**Pull request by pierrechtux**
## What does this PR do?

Just change a small typo in documentation.

## Why is this change important?

"virtualenv" was obviously misspelt as "virualenv".

### CODE REVIEW

**Comment by return42** [comment]
Thanks for fixing my typos :)

Please do not add old commits from yours and mine into a PR / Rebase your branch to current searx:master and force push / thanks!

**Comment by pierrechtux** [comment]
Sorry for mixing things; I'll rebase this.

**Comment by pierrechtux** [comment]
This time, it should be much more simpler.
Sorry for the mess.

**Review by return42 — APPROVED** [review]
Thanks!

**Pull request merged**
