### PR TITLE
Update default.html to move results URL higher up in Legacy theme

### PR DESCRIPTION
**Pull request by geckolinux**
Update default.html to move results URL higher up in Legacy theme

### CODE REVIEW

**Comment by unixfox** [comment]
Could you please rename your commit message? It doesn't define what has been changed.

**Comment by return42** [comment]
Thanks for you contribution! .. please read our 'How to contribute' guide and [choose meaning full commit messages,](https://asciimoo.github.io/searx/dev/contribution_guide.html#code) / thanks!

**Comment by geckolinux** [comment]
Sure, sorry I don't have much experience. Is this better now?
Also I'd appreciate a few pointers to make this same change to the Oscar theme.

**Comment by unixfox** [comment]
It's the commit name that needs to be changed: https://github.com/asciimoo/searx/pull/1833/commits.
If I had I would have explained to you how to do it but just search on your search engine it's really easy to do.

**Comment by return42** [comment]
Read https://asciimoo.github.io/searx/dev/quickstart.html .. a basic programming & git knowledge is needed / sorry.

**Pull request closed without merging**
