### PR TITLE
update und polish README

### PR DESCRIPTION
**Pull request by return42**
Preview is available at: https://github.com/return42/searx/blob/searx-next/README.rst

This PR should be merged after #1803 is merged / the preview is from my [searx-next branch](https://github.com/return42/searx/tree/searx-next) including #1803

### CODE REVIEW

**Review by kvch — APPROVED** [review]

**Review by kvch — CHANGES_REQUESTED** [review]
I would not remove so much information about running an instance and contact info.

**Comment by return42** [comment]
> I would not remove so much information about running an instance and contact info.

And I want to see PR #1803 merged first.  Building a searx instance requires more than just installing some pip packages. PR #1803 is a revise of the installation instruction https://return42.github.io/searx/admin/installation.html

**Comment by return42** [comment]
@kvch #1803 is now merged, do you have time to continue with the review of the README [#1951] / thanks!

**Review by asciimoo — APPROVED** [review]
Awesome, thanks!

**Pull request merged**
