### PR TITLE
General cookies

### PR DESCRIPTION
**Pull request by Cqoicebordel**
Allow a theme to have access to any cookie, and to store any cookie.
Modify Courgette to have a color picker.

### CODE REVIEW

**Comment by Cqoicebordel** [comment]
I toyed with the idea of only allowing in the "cookies" var, the cookies whose names began with the theme name, for privacy issue.
But, in the end, it's all searx. It's searx writing the cookie, and reading it, so there is no privacy issue.

**Comment by asciimoo** [comment]
What about handling the template assignment of the `request.cookies` inside the `render()` function instead of passing as a parameter?

**Comment by Cqoicebordel** [comment]
Of course ! Much better !

**Comment by asciimoo** [comment]
Great, thanks! =]

**Pull request merged**
