### PR TITLE
add voat.co engine

### LINKED ISSUE #773: request to add voat.co to social media engine list
voat.co is slowly gaining in popularity as a freedom of expression alternative to reddit

### PR DESCRIPTION
**Pull request by kvch**
Added as disabled by default as this engine is very slow to respond.

Closes #773

### CODE REVIEW

**Comment by kvch** [comment]
Oh, sorry. I pushed it to your repo unintentionally. :(

**Review by asciimoo — APPROVED** [review]

**Comment by asciimoo** [comment]
thanks

**Comment by VoatSearch** [comment]
Hey guys, can I suggest/request you change the Voat search engine to https://searchvoat.co? It runs much faster and produces much better results than voat.co.  Duckduckgo uses it for their !voat bang.  There's a subverse for it on Voat at https://voat.co/v/VoatSearch.  The template is https://searchvoat.co/?all={query}.  What do you think?

**Comment by kvch** [comment]
@VoatSearch Looks promising. However, I am not sure if I had found its source. Is https://github.com/fuerve/voat-search where it resides?

**Comment by VoatSearch** [comment]
The source isn't on github, does it need to be?

**Comment by kvch** [comment]
@VoatSearch No, I was just curious if it was open source or not.

**Comment by VoatSearch** [comment]
Not currently

**Pull request merged**
