### PR TITLE
Add a PWA plugin

### LINKED ISSUE #1713: [Feature] Make Searx a PWA
I was showing Searx to colleague when I thought that it might actually be nice to make it a Progressive Web App (PWA) and be able to install on my phone almost as if it was a Native App.

The [checklist to become a PWA](https://developers.google.com/web/progressive-web-apps/checklist) is rather simple: 
* Served over HTTPS (outside of the scope of this repo)
* **Provide a [Service Worker](https://developers.google.com/web/fundamentals/primers/service-workers/) to allow to load the app offline**
* **Provide a [Web App Manifest](https://developers.google.com/web/fundamentals/web-app-manifest) to describe the application's metadata**

The last points are rather easy to develop (already done it for custom apps), so if you're interested I might be able to help with this 😉

### PR DESCRIPTION
**Pull request by madmath03**
:sparkles: Add a plugin to turn searx into a PWA to close #1713

### CODE REVIEW

**Comment by emilylange** [comment]
There is already another PR #1712 you might want to check :)

**Comment by madmath03** [comment]
Interesting 😃
Thanks for the info @IndeedNotJames.
Funny to see someone submitted a PR only a few hours before the feature request with the same idea was posted, too bad I did not see it ^^

I will keep this PR open for now, since my implementation is slightly different and I do not know which one is better.

**Comment by madmath03** [comment]
Did a few tests and bug fixing on this PR.
I took some things from #1712 and also added support for apple touch icons.

Support for older themes have also been added.

In terms of interface, if the current browser supports PWA, an "_install_" link will appear between the "_about_" and "_preferences_" link:
* Oscar:
image
* Simple:
image
* Other default themes:
image

Clicking on it will display the browser's install popup and hide the link. If the user cancels the install popup, or install the app and then later deletes it, the link will appear again.
This is recommended to have a UI component to trigger the install, otherwise the browser will decide when to display the popup and it will be hard to trigger it again if canceled.

Translations will have to be set for this link but I think it can be done later.

And by the way, if you have Content Security Policy for your Searx instance, you might need to add `manifest-src 'self';` and `worker-src 'self';` to properly load the Web App Manifest.

**Comment by return42** [comment]
Merged this PR into my https://darmarit.cloud/searx/ (feel free to test).

I had to fix some issues with relative URLs, when scope is like `https://myhost/<application>/`. I prepared a clean patch for you at https://github.com/return42/searx/commit/6db2c20

May you like to cherry pick my fix into this PR? / Thanks!

**Comment by madmath03** [comment]
Hi @return42 ,

> Merged this PR into my https://darmarit.cloud/searx/ (feel free to test).
> 
> I had to fix some issues with relative URLs, when scope is like `https://myhost/<application>/`. I prepared a clean patch for you at [return42@6db2c20](https://github.com/return42/searx/commit/6db2c20)

Nice !

> May you like to cherry pick my fix into this PR? / Thanks!

As soon as I find the time I will do it 😉 
Thanks a lot for that and I'm glad to see you like what we did with this.

**Comment by madmath03** [comment]
Hi @return42 ,

I cherry picked your commit to this PR and also resolved merge conflicts due to updates on the master branch.

The CI `./manage.sh tests` is failing though I do not think it's related to these developments.

**Comment by return42** [comment]
FYI: after https://github.com/asciimoo/searx/pull/1938 gets merged, this could be implemented as external plugin.

Closed due to inactivity / ask to reopen / thanks!

**Comment by madmath03** [comment]
> FYI: after #1938 gets merged, this could be implemented as external plugin.
> 
> Closed due to inactivity / ask to reopen / thanks!

Hi @return42 

When I saw your comment there I thought this was closed because you're not sure about PWA and you would prefer to have this into an external plugin, but "_Closed due to inactivity / ask to reopen / thanks!_" makes me think you were expected some modifications... is that correct ? If so, which ones ?

**Comment by return42** [comment]
Can't speak for repo owner @asciimoo but I did not see this as an internal plugin maintained by the searx team.  Do you ask for merge into master or is this just a study? / I think this more of an interesting study.

In the meantime I have also changed my mind, I no longer believe that this is a good idea / sorry, it is just my personal opinion.

I can reopen this issue if you want ... but I think that won't change anything / may be I'm wrong.

**Comment by madmath03** [comment]
> Can't speak for repo owner @asciimoo but I did not see this as an internal plugin maintained by the searx team. Do you ask for merge into master or is this just a study? / I think this more of an interesting study.

Mostly asking in case I misunderstood the reason for closing the PR.

> In the meantime I have also changed my mind, I no longer believe that this is a good idea / sorry, it is just my personal opinion.
> I can reopen this issue if you want ... but I think that won't change anything / may be I'm wrong.

That's a shame because I do believe this would benefit Searx without really any drawbacks, but it's alright.

Though I would be curious to know about @asciimoo's opinion on this, I'm just going to wait for #1938 to land and provide this as an external plugin (which by the way is a great idea) so this way anyone can decide if they want it or not 😉

**Comment by asciimoo** [comment]
I still think that this is a useful addition. I kept it open just because of #1938 . I'm going to focus more on plugin decoupling, so we can finalize this contribution too. Is it okay to you @madmath03 ?

UPDATE:
I agree with @return42 that it would be better as an external plugin.

**Comment by madmath03** [comment]
That's good for me @asciimoo.

I'm looking forward to #1938 being ready 😃

**Comment by return42** [comment]
I tested PWA with Chrome & FFox and got some doubts what the benefit is:

- [From my personal opinion, it is not useful that links are opened in the PWA App, which is not a fully flexed browser (missing forward/backward buttons URL line etc)](https://github.com/asciimoo/searx/issues/1713#issuecomment-569205711)
- [.. and now it is getting really weird: Type ALT left n-times in your Google-Chrome PWA and you will see a google search bar in your PWA .. WTF did google here!?!?! I haven't tested with Chromium.](https://github.com/asciimoo/searx/issues/1713#issuecomment-569407362)
- [Another problem I see, the browser manufactures have different opinion of what a PWA is: Is PWA a real application or is it just a browser app with less buttons and a lot of bloatware inside? ..IMO this is not a real application, it is a kind of bloatware what Chrome does.](https://github.com/asciimoo/searx/issues/1713#issuecomment-573592926)

Thoughts?

**Comment by madmath03** [comment]
> I tested PWA with Chrome & FFox and got some doubts what the benefit is:
> 
> * [From my personal opinion, it is not useful that links are opened in the PWA App, which is not a fully flexed browser (missing forward/backward buttons URL line etc)](https://github.com/asciimoo/searx/issues/1713#issuecomment-569205711)

As mentioned in https://github.com/asciimoo/searx/issues/1713#issuecomment-569293407, this was fixed by switching to `minimal-ui` display in https://github.com/Monogramm/searx/commit/627c303931af2d2455a986bff6faf09efb871266.

Also, the main objective is to provide a "_native-like_" experience by adding an icon on your smartphone and starting the Searx app instantly.
This feels a lot more natural nowadays with apps everywhere and might help "_non-nerds_" to install and use Searx on their device, especially if the install process is super easy.

By the way, thanks to Service Workers cache management, the PWA cached resources will automatically be updated if a new version is available online.

> * [.. and now it is getting really weird: Type ALT left n-times in your Google-Chrome PWA and you will see a google search bar in your PWA .. WTF did google here!?!?! I haven't tested with Chromium.](https://github.com/asciimoo/searx/issues/1713#issuecomment-569407362)

Tested several times with Brave, Chrome and Firefox, and never got this behavior 😕 

> * [Another problem I see, the browser manufactures have different opinion of what a PWA is: Is PWA a real application or is it just a browser app with less buttons and a lot of bloatware inside? ..IMO this is not a real application, it is a kind of bloatware what Chrome does.](https://github.com/asciimoo/searx/issues/1713#issuecomment-573592926)

Well, from my understanding, the principle of PWAs is to "_cache your web app on your device and then run it in a separate browser process / entry_", so it is by definition just a browser running a cached version of your web app.

Since it's relying on the browser, of course each manufacturer will have a different approach and implementation, nothing new with that when it comes to new web features, but the bloatware aspect is a bit tricky to confirm and I do not think I ever read an article or analysis on that...

IMO, I feel like the "_way it's packaged_" is less important than the "_added value_" to the user, as long as the package does not insert trackers or such of course... but since Firefox (and others) can be used to install a PWA (not just Chrome), I would say that you should be safe on that regard.

**Pull request closed without merging**
