### PR TITLE
[enh] add DOI resolver from sci-hub / replace default DOI

### LINKED ISSUE #2693: DOI resolver: replace sci-hub.tw with alternative domains
Sci-Hub is no longer operating through the [sci-hub.tw](https://sci-hub.tw) domain, so it can't be used as a DOI resolver.
Better to redirect the Sci-Hub DOI resolver to a randomly-selected domain from the following list:
sci-hub.se
sci-hub.do
scihubtw.tw
sci-hub.it.nf
sci-hub.st
sci-hub.bar

### PR DESCRIPTION
**Pull request by 1366613**
Read more about DOI at [Wikipedia](https://en.wikipedia.org/wiki/Digital_object_identifier) and at [doi.org](https://www.doi.org/). It's identification system for scientific articles. DOI is to scientific papers what ISBN is to books.
What these DOI resolvers do is that you give them the DOI number of any specific scientific paper(e.g., [10.1109/5.771073](https://doi.org/10.1109/5.771073)) and then they'll give the PDF version of that paper in return; but free of charge, because scientific papers are mostly distributed by a handful of big corporations and are well behind paywalls.

## What does this PR do?

Add DOI resolver domains from sci-hub and replace the default DOI resolver.

## Why is this change important?

The existing default DOI resolver https://sci-hub.tw redirects to insecure side

## How to test this PR locally?
```
make run
```
- Visit config at http://127.0.0.1:8888/config and check default_doi_resolver and doi_resolvers
- Open preferences and activate the "Open Access DOI rewrite" plugin
- Tab "General" select "Open Access DOI resolver"
- Save / run a query in category 'science' and check DOI URLs

## Related issues

Closes #2693, #2260 and #910

### CODE REVIEW

**Comment by unixfox** [comment]
Please stop creating duplicate pull request and learn how to use git, it's not complicated to squash you have a lot of tutorials on the internet for that.

So now rename your commit to a better name because the commit name is not descriptive at all. And without recreating a new pull request :)

Thanks for the explanation though.

**Review by return42 — CHANGES_REQUESTED** [review]
Please rename the commit / https://github.com/searx/searx/pull/2706#issuecomment-810787315 / I would suggest a commit message like:

    [enh] add DOI resolver from sci-hub / replace default DOI

    The existing default DOI resolver https://sci-hub.tw redirects to insecure side.
    Add DOI resolver domains from sci-hub and replace the default DOI resolver.

    
For the next time, please fill out the https://github.com/searx/searx/blob/master/PULL_REQUEST_TEMPLATE.md

## What does this PR do?

Add DOI resolver domains from sci-hub and replace the default DOI resolver.

## Why is this change important?

The existing default DOI resolver https://sci-hub.tw redirects to insecure side

## How to test this PR locally?

    make run

1. Visit config at http://127.0.0.1:8888/config and check `default_doi_resolver` and `doi_resolvers`
2. Open preferences and 

- activate the "Open Access DOI rewrite" plugin
- Tab "General" select "Open Access DOI resolver" 
-  Save / run a query in category 'science' and check DOI URLs

## Author's checklist

???

## Related issues

Closes #2693 and also #2260 and #910

**Review by return42 — CHANGES_REQUESTED** [review]
Can you also mod the `searx/settings_robot.yml` / thanks!
```diff
modified   searx/settings_robot.yml
@@ -43,6 +43,10 @@ doi_resolvers :
   oadoi.org : 'https://oadoi.org/'
   doi.org : 'https://doi.org/'
   doai.io  : 'https://dissem.in/'
-  sci-hub.tw : 'https://sci-hub.tw/'
+  sci-hub.se : 'https://sci-hub.se/'
+  sci-hub.do : 'https://sci-hub.do/'
+  scihubtw.tw : 'https://scihubtw.tw/'
+  sci-hub.st : 'https://sci-hub.st/'
+  sci-hub.bar : 'https://sci-hub.bar/'
 
-default_doi_resolver : 'sci-hub.tw'
+default_doi_resolver : 'sci-hub.do'
```

**Comment by return42** [comment]
FYI: I found a bug about the 'default_doi_resolver' setting, see my patch #2707

**Comment by 1366613** [comment]
@unixfox I know how to use git. That was a mistake. Sorry.

**Comment by 1366613** [comment]
@return42
> Can you also mod the `searx/settings_robot.yml` / thanks!

Done. Please check.

**Comment by return42** [comment]
> @unixfox I know how to use git. That was a mistake. Sorry.

OK, then please [squash the commit into one](https://github.com/searx/searx/pull/2706#issuecomment-810787315)  and give a [more meaningful commit message](https://github.com/searx/searx/pull/2706#pullrequestreview-625019861).

**Comment by kvch** [comment]
@aurora-vasiliev Please also rebase your PR instead of merging our master branch into yours.

**Review by kvch — DISMISSED** [review]

**Review by kvch — APPROVED** [review]

**Pull request merged**
