### PR TITLE
Refactor code quality issues

### PR DESCRIPTION
**Pull request by akshgpt7**
#### Description
Hi, I ran DeepSource analysis on my fork of the repo, and found some interesting [code quality and performance issues](https://deepsource.io/gh/akshgpt7/searx/) to consider.

This PR fixes a few of the issues detected for you to assess if it is right for you.

#### Summary of changes
- Iterate dictionary directly instead of calling `.keys()`.
- Remove unnecessary generators.
- Refactor unnecessary use of comprehension.
- Remove usage of `len()` for comparison.
- Refactor `if` expression.
- Add `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

## Why is this change important?
The PR fixes some Anti-Patterns and Performance issues that can improve the general code quality and performance here.

### CODE REVIEW

**Comment by return42** [comment]
Does DeepSource needs to sign up?

I had a look at the issues DeepSource reported (your link), to me it exactly looks like a pylint result without disabling any reports / FYI: we have a `make tests.pylint` in our quality gate / but for the first we disabled many issues

https://github.com/searx/searx/blob/11070e57449caf86fd6087116e24bed8bea54e63/Makefile#L9-L10

Compare line 10 with  https://deepsource.io/gh/akshgpt7/searx/issue/PYL-E0602/occurrences

Since DeepSource does not more than a pylint, I think it is better we tighten our pylint rules in the quality gate from  time to time.

**Comment by akshgpt7** [comment]
@return42 In addition to the pylint rules, DeepSource also detects some performance issues, bug-risks and security vulnerabilities. Also, you can Autofix them with just one click. DeepSource will flag only those changes which occur in a particular patch/PR, which will make the code review process faster.
Just like the pylint config, you can selectively choose which issues to ignore in DeepSource too.
Feel free to reach out or check out the [docs](https://deepsource.io/docs) if you have any questions :)

**Comment by return42** [comment]
I'm not the maintainer, but I will give my very, very ... very personal opinion:

I think monitoring code is something that could help to eliminate common issues.

> DeepSource also detects some performance issues, bug-risks and security vulnerabilities. Also, you can Autofix them with just one click. 

I see that very critically / Performance optimization needs a knowledge about the application, the use cases and the used technologies.  You don't get performance just by looking at a few lines of code.

From an educational point of view such click-and-optimize tools are even dangerous because they lead to a certain dumbing down of the developers.  A developer should know what he is doing. If there is a gap of knowledge you have to take the time and learn what is needed to get the job done well.

It is hard to learn and so easy to use a tool .. and that are the reasons why such tools make us stupid.

I've seen things you people wouldn't believe. Programmers that have been replaced by tools.  Attack ships on fire off the shoulder of Orion.  I watched C-beams glitter in the dark near the Tannhäuser Gate.  All those moments will be lost in time, like tears in rain. Time to die.

**Comment by unixfox** [comment]
Hello,

Thank you for your contribution. Unfortunately we don't want to use additional tools, but we would gladly review your changes if you remove the `.deepsource.toml` file.

**Comment by akshgpt7** [comment]
@unixfox No worries, I've removed the `.deepsource.toml` file :)

**Comment by akshgpt7** [comment]
@unixfox any updates on this?

**Pull request closed without merging**
