### PR TITLE
Add Crossref search engine and DOAI rewrite plugin

### PR DESCRIPTION
**Pull request by davidar**

### CODE REVIEW

**Comment by asciimoo** [comment]
Wouldn't be better to create a specific engine which rewrites the results by default instead of introducing a new plugin which also checks all other engine's results?

**Comment by davidar** [comment]
@asciimoo Possibly?

The plugin isn't specific to this engine, as any engine could potentially return DOI links. I probably should have made these two separate PRs.

**Comment by davidar** [comment]
@asciimoo Done.

I also updated the plugin so that it's able to catch more links now (not limited to just the doi.org domain)

**Comment by asciimoo** [comment]
great, thanks

**Pull request merged**
